// Índice de INTENCIONES: describes lo que quieres hacer con tus palabras
// y el buscador te dice qué herramienta es la que estás buscando.
// q = lo que quieres hacer · k = otras formas de decirlo · js/py = lo que necesitas
// que = qué es exactamente · ej = ejemplo real
const INTENCIONES = [
  // ---------- TEXTO ----------
  {
    q: "Cambiar un número a texto",
    k: "convertir numero a string cadena pasar transformar tipo texto number to string",
    cat: "Conversión",
    js: "String(valor)  ·  también `${valor}`",
    py: "str(valor)",
    que: "Convierte un valor numérico en una cadena de texto, para poder concatenarlo, mostrarlo en pantalla o guardarlo.",
    ej: 'const edad = 42;\nconst texto = String(edad);\nconsole.log("Tengo " + texto + " años");',
  },
  {
    q: "Cambiar un texto a número",
    k: "convertir string a numero int parsear input formulario suma no funciona concatena string to number",
    cat: "Conversión",
    js: "Number(texto)  ·  parseInt(texto)  ·  parseFloat(texto)",
    py: "int(texto)  ·  float(texto)",
    que: "Convierte texto en número. Es imprescindible con los valores de inputs y formularios, que SIEMPRE llegan como texto: sin convertirlos, sumar concatena en vez de sumar.",
    ej: 'const texto = "42";\nconsole.log(texto + 8);          // "428"  ← concatena\nconsole.log(Number(texto) + 8);  // 50    ← suma',
  },
  {
    q: "Contar cuántas letras o caracteres tiene un texto",
    k: "contador de letras longitud caracteres cuantas letras tamaño largo length",
    cat: "Texto",
    js: "texto.length",
    py: "len(texto)",
    que: "Devuelve el número de caracteres del texto (contando espacios). Es una propiedad, no una función: va sin paréntesis en JavaScript.",
    ej: 'const frase = "Hola mundo";\nconsole.log(frase.length); // → 10',
  },
  {
    q: "Contar cuántas palabras tiene un texto",
    k: "contador de palabras cuantas palabras contar palabras textarea",
    cat: "Texto",
    js: "texto.trim().split(/\\s+/).filter(Boolean).length",
    py: "len(texto.split())",
    que: "Se recorta el texto, se parte por los espacios (uno o varios) y se cuentan los trozos. El filtro evita contar una 'palabra fantasma' cuando el texto está vacío.",
    ej: 'const texto = "  hola   mundo cruel ";\nconst palabras = texto.trim().split(/\\s+/).filter(Boolean);\nconsole.log(palabras.length); // → 3',
  },
  {
    q: "Quitar los espacios del principio y del final",
    k: "limpiar espacios sobrantes trim recortar espacios en blanco",
    cat: "Texto",
    js: "texto.trim()",
    py: "texto.strip()",
    que: "Elimina los espacios (y saltos de línea) que sobran al principio y al final, sin tocar los de dentro. Casi obligatorio al validar lo que escribe un usuario.",
    ej: 'const entrada = "   ana   ";\nconsole.log(entrada.trim()); // → "ana"',
  },
  {
    q: "Pasar un texto a mayúsculas o a minúsculas",
    k: "mayusculas minusculas capitalizar upper lower normalizar comparar sin mayusculas",
    cat: "Texto",
    js: "texto.toUpperCase()  ·  texto.toLowerCase()",
    py: "texto.upper()  ·  texto.lower()",
    que: "Cambia todo el texto de caso. Se usa muchísimo antes de comparar dos textos, para que 'Ana' y 'ana' cuenten como iguales.",
    ej: 'const buscado = "MANZANA";\nconst dato = "Manzana";\nconsole.log(dato.toLowerCase() === buscado.toLowerCase()); // → true',
  },
  {
    q: "Comprobar si un texto contiene una palabra",
    k: "buscar dentro de un texto incluye contiene existe substring includes",
    cat: "Texto",
    js: "texto.includes(\"palabra\")",
    py: '"palabra" in texto',
    que: "Devuelve true o false según si el fragmento aparece dentro del texto. Es la base de cualquier buscador o filtro.",
    ej: 'const fruta = "manzana";\nif (fruta.includes("man")) {\n  console.log("Coincide con la búsqueda");\n}',
  },
  {
    q: "Partir un texto en trozos (por comas, espacios...)",
    k: "dividir separar cortar texto csv split trocear",
    cat: "Texto",
    js: 'texto.split(",")',
    py: 'texto.split(",")',
    que: "Corta el texto por el separador que le indiques y devuelve una lista con los trozos. Ideal para leer datos separados por comas.",
    ej: 'const csv = "rojo,verde,azul";\nconsole.log(csv.split(",")); // → ["rojo", "verde", "azul"]',
  },
  {
    q: "Sustituir una palabra por otra dentro de un texto",
    k: "reemplazar cambiar palabra replace sustituir texto",
    cat: "Texto",
    js: 'texto.replace("viejo", "nuevo")  ·  .replaceAll() para todas',
    py: 'texto.replace("viejo", "nuevo")',
    que: "Cambia una coincidencia por otro texto. Ojo: en JavaScript, replace() cambia solo la primera; replaceAll() cambia todas. En Python, replace() cambia todas.",
    ej: 'const frase = "hola mundo";\nconsole.log(frase.replace("mundo", "JS")); // → "hola JS"',
  },
  {
    q: "Coger solo un trozo de un texto",
    k: "extraer parte subcadena recortar primeros caracteres slice substring",
    cat: "Texto",
    js: "texto.slice(inicio, fin)",
    py: "texto[inicio:fin]",
    que: "Extrae la porción del texto entre dos posiciones, empezando a contar en 0. No modifica el texto original.",
    ej: 'const fruta = "manzana";\nconsole.log(fruta.slice(0, 3)); // → "man"',
  },
  {
    q: "Rellenar con ceros a la izquierda (05, 09...)",
    k: "formato hora reloj dos digitos cero delante padstart rellenar",
    cat: "Texto",
    js: 'String(numero).padStart(2, "0")',
    py: 'str(numero).zfill(2)  ·  f"{numero:02d}"',
    que: "Rellena por la izquierda hasta llegar a la longitud indicada. Es lo que se usa para mostrar relojes y cronómetros como 09:05 en vez de 9:5.",
    ej: 'const minutos = 5;\nconsole.log(String(minutos).padStart(2, "0")); // → "05"',
  },
  {
    q: "Unir varios textos en uno",
    k: "concatenar juntar pegar interpolar plantilla template string unir",
    cat: "Texto",
    js: "`Hola ${nombre}`  ·  \"a\" + \"b\"  ·  array.join(\" \")",
    py: 'f"Hola {nombre}"  ·  "a" + "b"  ·  " ".join(lista)',
    que: "Para pegar textos con variables dentro, las plantillas (con acentos graves en JS, f-strings en Python) son más legibles que ir sumando con +.",
    ej: 'const nombre = "Ana";\nconsole.log(`Hola ${nombre}, bienvenida`);',
  },

  // ---------- NÚMEROS ----------
  {
    q: "Redondear un número",
    k: "redondear decimales entero mas cercano round precio",
    cat: "Matemáticas",
    js: "Math.round(numero)  ·  numero.toFixed(2) para 2 decimales",
    py: "round(numero)  ·  round(numero, 2)",
    que: "Math.round() redondea al entero más cercano. Si lo que quieres es mostrar un precio con dos decimales, toFixed(2) te devuelve el texto ya formateado.",
    ej: "const precio = 19.567;\nconsole.log(Math.round(precio));    // → 20\nconsole.log(precio.toFixed(2));     // → \"19.57\"",
  },
  {
    q: "Quitar los decimales hacia abajo",
    k: "truncar redondear abajo entero inferior floor indice aleatorio",
    cat: "Matemáticas",
    js: "Math.floor(numero)",
    py: "math.floor(numero)  ·  int(numero)",
    que: "Redondea siempre hacia abajo. Es la pieza que acompaña a Math.random() para obtener un índice entero válido de un array.",
    ej: "console.log(Math.floor(4.9)); // → 4",
  },
  {
    q: "Sacar un número al azar",
    k: "aleatorio random azar suerte numero random entre",
    cat: "Matemáticas",
    js: "Math.random()  ·  entero: Math.floor(Math.random() * max)",
    py: "random.random()  ·  random.randint(1, max)",
    que: "Math.random() da un decimal entre 0 y 1. Para un entero en un rango, se multiplica por el máximo y se redondea hacia abajo.",
    ej: "// número entero del 1 al 6 (un dado)\nconst dado = Math.floor(Math.random() * 6) + 1;\nconsole.log(dado);",
  },
  {
    q: "Elegir un elemento al azar de una lista",
    k: "aleatorio array lista sortear elegir random choice",
    cat: "Arrays y objetos",
    js: "lista[Math.floor(Math.random() * lista.length)]",
    py: "random.choice(lista)",
    que: "Se genera un índice aleatorio válido (entre 0 y la longitud - 1) y se accede a esa posición del array.",
    ej: 'const colores = ["rojo", "verde", "azul"];\nconst elegido = colores[Math.floor(Math.random() * colores.length)];\nconsole.log(elegido);',
  },
  {
    q: "Sacar el número más alto o más bajo",
    k: "maximo minimo mayor menor max min puntuacion record",
    cat: "Matemáticas",
    js: "Math.max(...lista)  ·  Math.min(...lista)",
    py: "max(lista)  ·  min(lista)",
    que: "Math.max recibe números sueltos, así que si tienes un array hay que expandirlo con el operador spread (...).",
    ej: "const puntos = [3, 9, 2];\nconsole.log(Math.max(...puntos)); // → 9",
  },
  {
    q: "Quitar el signo negativo de un número",
    k: "valor absoluto positivo diferencia distancia abs",
    cat: "Matemáticas",
    js: "Math.abs(numero)",
    py: "abs(numero)",
    que: "Devuelve el valor sin signo. Se usa para calcular diferencias o distancias, donde da igual el orden de la resta.",
    ej: "const diferencia = 5 - 12;\nconsole.log(Math.abs(diferencia)); // → 7",
  },
  {
    q: "Sumar todos los números de una lista",
    k: "total suma acumular carrito precio reduce sumatorio",
    cat: "Arrays y objetos",
    js: "lista.reduce((total, n) => total + n, 0)",
    py: "sum(lista)",
    que: "reduce() recorre el array acumulando un único resultado. El 0 del final es el valor inicial del acumulador.",
    ej: "const precios = [10, 25, 5];\nconst total = precios.reduce((acc, n) => acc + n, 0);\nconsole.log(total); // → 40",
  },

  // ---------- LISTAS / ARRAYS ----------
  {
    q: "Añadir un elemento al final de una lista",
    k: "agregar meter push insertar array lista nuevo elemento",
    cat: "Arrays y objetos",
    js: "lista.push(elemento)",
    py: "lista.append(elemento)",
    que: "Añade el elemento al final, modificando el array original. Es el paso típico al guardar algo que ha escrito el usuario.",
    ej: 'const tareas = ["comprar"];\ntareas.push("estudiar");\nconsole.log(tareas); // → ["comprar", "estudiar"]',
  },
  {
    q: "Quitar un elemento de una lista",
    k: "borrar eliminar remove quitar splice filter delete array",
    cat: "Arrays y objetos",
    js: "lista.filter(x => x.id !== id)  ·  lista.pop() para el último",
    py: "lista.remove(valor)  ·  lista.pop()",
    que: "Para borrar un elemento concreto, filter() crea una lista nueva sin él (más seguro que modificar la original mientras la recorres). pop() solo quita el último.",
    ej: "let tareas = [{id: 1}, {id: 2}];\ntareas = tareas.filter(t => t.id !== 1);\nconsole.log(tareas); // → [{id: 2}]",
  },
  {
    q: "Recorrer una lista uno por uno",
    k: "iterar bucle for each recorrer array cada elemento pintar lista",
    cat: "Bucles",
    js: "for (const item of lista) { ... }  ·  lista.forEach(item => ...)",
    py: "for item in lista:",
    que: "Cuando solo necesitas los valores (no la posición), for...of es lo más limpio. forEach hace lo mismo en forma de función.",
    ej: 'const frutas = ["manzana", "pera"];\nfor (const fruta of frutas) {\n  console.log(fruta);\n}',
  },
  {
    q: "Filtrar una lista para quedarme solo con algunos",
    k: "filtrar buscador busqueda en tiempo real filter criterio condicion",
    cat: "Arrays y objetos",
    js: "lista.filter(item => condicion)",
    py: "[x for x in lista if condicion]",
    que: "Crea una lista NUEVA solo con los elementos que cumplen la condición; la original no se toca. Es el motor de cualquier buscador en tiempo real.",
    ej: 'const frutas = ["manzana", "pera", "melon"];\nconst conM = frutas.filter(f => f.startsWith("m"));\nconsole.log(conM); // → ["manzana", "melon"]',
  },
  {
    q: "Transformar todos los elementos de una lista",
    k: "map convertir cada elemento transformar precios con iva nueva lista",
    cat: "Arrays y objetos",
    js: "lista.map(item => nuevoValor)",
    py: "[transformar(x) for x in lista]",
    que: "Devuelve una lista nueva del mismo tamaño, con cada elemento transformado. Se usa para aplicar un cálculo o formato a toda una colección.",
    ej: "const precios = [10, 20];\nconst conIva = precios.map(p => p * 1.21);\nconsole.log(conIva); // → [12.1, 24.2]",
  },
  {
    q: "Buscar un elemento concreto en una lista",
    k: "encontrar find buscar por id existe indexof includes",
    cat: "Arrays y objetos",
    js: "lista.find(x => x.id === id)  ·  lista.includes(valor)",
    py: "next((x for x in lista if x.id == id), None)  ·  valor in lista",
    que: "find() devuelve el primer elemento que cumple la condición (o undefined). includes() solo dice si existe o no, con true/false.",
    ej: "const usuarios = [{id: 1, nombre: \"Ana\"}];\nconst ana = usuarios.find(u => u.id === 1);\nconsole.log(ana.nombre); // → \"Ana\"",
  },
  {
    q: "Ordenar una lista",
    k: "ordenar alfabeticamente de mayor a menor sort ordenacion clasificar",
    cat: "Arrays y objetos",
    js: "lista.sort()  ·  numeros.sort((a, b) => a - b)",
    py: "lista.sort()  ·  sorted(lista)",
    que: "sort() sin argumentos ordena como TEXTO (por eso 10 va antes que 9). Para números hay que pasarle la función de comparación (a, b) => a - b.",
    ej: "const numeros = [10, 9, 100];\nconsole.log([...numeros].sort());            // → [10, 100, 9] ❌\nconsole.log([...numeros].sort((a,b) => a-b)); // → [9, 10, 100] ✅",
  },
  {
    q: "Contar cuántas veces aparece algo en una lista",
    k: "contar repeticiones cuantas veces count ocurrencias",
    cat: "Arrays y objetos",
    js: "lista.filter(x => x === valor).length",
    py: "lista.count(valor)",
    que: "Se filtran las coincidencias y se cuenta el tamaño del resultado.",
    ej: "const votos = [\"si\", \"no\", \"si\"];\nconsole.log(votos.filter(v => v === \"si\").length); // → 2",
  },
  {
    q: "Juntar dos listas en una",
    k: "unir combinar concatenar arrays fusionar concat spread",
    cat: "Arrays y objetos",
    js: "[...listaA, ...listaB]  ·  listaA.concat(listaB)",
    py: "listaA + listaB  ·  listaA.extend(listaB)",
    que: "El spread (...) crea una lista nueva con el contenido de ambas, sin modificar las originales.",
    ej: "const a = [1, 2];\nconst b = [3, 4];\nconsole.log([...a, ...b]); // → [1, 2, 3, 4]",
  },
  {
    q: "Copiar una lista sin modificar la original",
    k: "clonar copia duplicar array referencia mutacion spread",
    cat: "Arrays y objetos",
    js: "const copia = [...original]",
    py: "copia = original.copy()  ·  original[:]",
    que: "Asignar directamente (b = a) NO copia: ambas variables apuntan al mismo array y modificar una cambia la otra. El spread sí crea una copia real.",
    ej: "const original = [1, 2];\nconst copia = [...original];\ncopia.push(3);\nconsole.log(original); // → [1, 2] intacto",
  },
  {
    q: "Saber cuántos elementos tiene una lista",
    k: "tamaño longitud cuantos elementos length contar items",
    cat: "Arrays y objetos",
    js: "lista.length",
    py: "len(lista)",
    que: "Propiedad con el número de elementos. Sirve también para saber si está vacía: lista.length === 0.",
    ej: 'const tareas = ["a", "b"];\nif (tareas.length === 0) console.log("No hay tareas");',
  },

  // ---------- OBJETOS ----------
  {
    q: "Sacar los nombres de las propiedades de un objeto",
    k: "claves keys propiedades objeto recorrer campos",
    cat: "Arrays y objetos",
    js: "Object.keys(objeto)",
    py: "objeto.keys()",
    que: "Devuelve un array con los nombres de las propiedades, que ya puedes recorrer como cualquier lista.",
    ej: 'const persona = { nombre: "Ana", edad: 30 };\nconsole.log(Object.keys(persona)); // → ["nombre", "edad"]',
  },
  {
    q: "Recorrer un objeto (clave y valor a la vez)",
    k: "iterar objeto entries items pares clave valor for in",
    cat: "Arrays y objetos",
    js: "for (const [clave, valor] of Object.entries(objeto))",
    py: "for clave, valor in objeto.items():",
    que: "entries() convierte el objeto en pares [clave, valor], que se pueden desestructurar directamente en el bucle.",
    ej: 'const persona = { nombre: "Ana", edad: 30 };\nfor (const [clave, valor] of Object.entries(persona)) {\n  console.log(clave, "=", valor);\n}',
  },
  {
    q: "Sacar varias propiedades de un objeto a variables",
    k: "desestructurar destructuring extraer campos objeto atajo",
    cat: "Arrays y objetos",
    js: "const { nombre, edad } = persona;",
    py: "nombre, edad = persona['nombre'], persona['edad']",
    que: "La desestructuración crea variables con el mismo nombre que las propiedades, en una sola línea.",
    ej: 'const persona = { nombre: "Ana", edad: 30 };\nconst { nombre, edad } = persona;\nconsole.log(nombre); // → "Ana"',
  },
  {
    q: "Copiar un objeto cambiando solo un campo",
    k: "actualizar objeto inmutable spread copia modificar propiedad",
    cat: "Arrays y objetos",
    js: "const nuevo = { ...objeto, campo: valorNuevo }",
    py: "nuevo = {**objeto, 'campo': valor_nuevo}",
    que: "Crea un objeto nuevo con todo lo del original y el campo indicado sobrescrito. Es el patrón estándar para actualizar sin mutar.",
    ej: 'const tarea = { id: 1, hecha: false };\nconst actualizada = { ...tarea, hecha: true };\nconsole.log(actualizada); // → { id: 1, hecha: true }',
  },

  // ---------- BUCLES ----------
  {
    q: "Repetir algo un número exacto de veces",
    k: "bucle for repetir n veces contador iterar numero fijo",
    cat: "Bucles",
    js: "for (let i = 0; i < n; i++) { ... }",
    py: "for i in range(n):",
    que: "El bucle con contador es la herramienta cuando sabes de antemano cuántas repeticiones necesitas.",
    ej: "for (let i = 0; i < 5; i++) {\n  console.log(i); // 0,1,2,3,4\n}",
  },
  {
    q: "Repetir algo hasta que se cumpla una condición",
    k: "while mientras bucle indefinido hasta que repetir condicion",
    cat: "Bucles",
    js: "while (condicion) { ... }",
    py: "while condicion:",
    que: "Cuando el número de vueltas no se sabe de antemano y depende de una condición, el bucle while es el adecuado. Cuidado con actualizar la condición dentro para no crear un bucle infinito.",
    ej: "let intentos = 0;\nwhile (intentos < 3) {\n  intentos++;\n}",
  },
  {
    q: "Salir de un bucle antes de tiempo",
    k: "break parar cortar bucle encontrado dejar de buscar salir",
    cat: "Bucles",
    js: "break",
    py: "break",
    que: "Detiene el bucle por completo. Se usa en cuanto ya conseguiste lo que buscabas y seguir iterando sería trabajo desperdiciado.",
    ej: "for (const n of numeros) {\n  if (n === buscado) break;\n}",
  },
  {
    q: "Saltarme una vuelta del bucle",
    k: "continue saltar ignorar elemento vacio siguiente iteracion",
    cat: "Bucles",
    js: "continue",
    py: "continue",
    que: "Salta directamente a la siguiente vuelta sin ejecutar el resto del bloque, pero sin abandonar el bucle.",
    ej: "for (const item of lista) {\n  if (!item) continue; // ignora vacíos\n  procesar(item);\n}",
  },

  // ---------- FUNCIONES ----------
  {
    q: "Reutilizar el mismo código en varios sitios",
    k: "funcion crear funcion evitar repetir codigo duplicado reutilizar",
    cat: "Funciones",
    js: "function nombre(parametros) { ... }  ·  const f = (a) => a * 2",
    py: "def nombre(parametros):",
    que: "En cuanto la misma lógica aparece en más de un sitio, debe vivir en una función: un único lugar que corregir si algo cambia.",
    ej: "function calcularIva(precio) {\n  return precio * 1.21;\n}\nconsole.log(calcularIva(100)); // → 121",
  },
  {
    q: "Que una función devuelva un resultado",
    k: "return devolver resultado valor salida funcion undefined",
    cat: "Funciones",
    js: "return valor",
    py: "return valor",
    que: "return termina la función y entrega el valor a quien la llamó. Sin return, la función devuelve undefined (None en Python).",
    ej: "function doble(x) {\n  return x * 2;\n}\nconst r = doble(5); // → 10",
  },
  {
    q: "Que un parámetro tenga un valor por defecto",
    k: "parametro opcional valor por defecto default argumento no pasado",
    cat: "Funciones",
    js: 'function saludar(nombre = "invitado") { ... }',
    py: "def saludar(nombre='invitado'):",
    que: "Si quien llama a la función no pasa ese dato, se usa el valor indicado. Evita tener que comprobar 'si no vino nada' dentro.",
    ej: 'function saludar(nombre = "invitado") {\n  return "Hola " + nombre;\n}\nconsole.log(saludar()); // → "Hola invitado"',
  },

  // ---------- DOM ----------
  {
    q: "Coger un elemento del HTML",
    k: "seleccionar elemento dom id clase queryselector getelementbyid capturar",
    cat: "DOM",
    js: 'document.getElementById("id")  ·  document.querySelector(".clase")',
    py: null,
    que: "getElementById busca por id exacto. querySelector acepta cualquier selector CSS (.clase, #id, etiqueta) y devuelve el primero que coincida.",
    ej: 'const boton = document.getElementById("enviar");\nconst caja = document.querySelector(".tarjeta");',
  },
  {
    q: "Coger todos los elementos que tengan una clase",
    k: "seleccionar varios todos elementos queryselectorall lista nodos",
    cat: "DOM",
    js: 'document.querySelectorAll(".clase")',
    py: null,
    que: "Devuelve una lista con TODOS los que coinciden (no solo el primero), que puedes recorrer con forEach.",
    ej: 'document.querySelectorAll(".item").forEach(el => {\n  el.classList.add("visible");\n});',
  },
  {
    q: "Cambiar el texto que se ve en pantalla",
    k: "actualizar texto mostrar resultado contenido textcontent innerhtml pintar",
    cat: "DOM",
    js: "elemento.textContent = valor",
    py: null,
    que: "textContent cambia el texto plano de un elemento. Es la opción segura frente a innerHTML, que interpreta HTML y puede introducir vulnerabilidades si el texto viene del usuario.",
    ej: 'const display = document.getElementById("resultado");\ndisplay.textContent = contador;',
  },
  {
    q: "Crear un elemento nuevo y meterlo en la página",
    k: "crear elemento dinamico añadir li lista createelement appendchild insertar",
    cat: "DOM",
    js: 'const li = document.createElement("li");\nlista.appendChild(li);',
    py: null,
    que: "createElement crea el nodo en memoria (aún no se ve) y appendChild lo inserta en la página. Son los dos pasos de cualquier lista dinámica.",
    ej: 'const li = document.createElement("li");\nli.textContent = "Nueva tarea";\ndocument.getElementById("lista").appendChild(li);',
  },
  {
    q: "Añadir o quitar una clase CSS",
    k: "classlist add remove toggle activar clase estilo marcar completada",
    cat: "DOM",
    js: "el.classList.add(\"activo\")  ·  .remove()  ·  .toggle()",
    py: null,
    que: "La forma limpia de cambiar estilos: en vez de tocar el CSS desde JS, activas o desactivas una clase ya definida en la hoja de estilos. toggle() la pone o la quita según esté.",
    ej: 'tarea.classList.toggle("completada");',
  },
  {
    q: "Cambiar un atributo (src, alt, href, disabled...)",
    k: "atributo setattribute imagen enlace deshabilitar boton propiedad html",
    cat: "DOM",
    js: 'el.setAttribute("alt", "texto")  ·  el.disabled = true',
    py: null,
    que: "setAttribute sirve para cualquier atributo HTML. Algunos, como disabled o value, también se pueden asignar directamente como propiedad.",
    ej: 'const img = document.querySelector("img");\nimg.setAttribute("alt", "Foto de perfil");',
  },
  {
    q: "Leer lo que el usuario escribió en un input",
    k: "input value formulario capturar texto escrito campo leer dato usuario",
    cat: "DOM",
    js: "input.value  ·  input.value.trim()",
    py: null,
    que: "La propiedad value contiene lo escrito, SIEMPRE como texto. Conviene aplicarle trim() para descartar entradas que solo tienen espacios.",
    ej: 'const texto = document.getElementById("nueva").value.trim();\nif (texto === "") return; // no añadir vacíos',
  },
  {
    q: "Borrar todo el contenido de un contenedor",
    k: "limpiar vaciar contenedor lista antes de pintar innerhtml vacio duplicados",
    cat: "DOM",
    js: 'contenedor.innerHTML = ""',
    py: null,
    que: "Vacía el contenedor antes de volver a pintarlo. Sin este paso, cada renderizado duplicaría los elementos ya existentes.",
    ej: 'function render(items) {\n  lista.innerHTML = "";\n  items.forEach(item => { /* ... */ });\n}',
  },

  // ---------- EVENTOS ----------
  {
    q: "Hacer que pase algo al pulsar un botón",
    k: "click boton evento escuchar addeventlistener pulsar reaccionar",
    cat: "Eventos",
    js: 'boton.addEventListener("click", () => { ... })',
    py: null,
    que: "Registra una función que se ejecutará cada vez que ocurra ese evento sobre ese elemento. Es la puerta de entrada de casi toda interacción.",
    ej: 'boton.addEventListener("click", () => {\n  contador++;\n  display.textContent = contador;\n});',
  },
  {
    q: "Reaccionar mientras el usuario escribe",
    k: "input evento tiempo real buscador teclear keyup escribiendo",
    cat: "Eventos",
    js: 'campo.addEventListener("input", () => { ... })',
    py: null,
    que: "El evento 'input' se dispara con cada cambio del valor (tecla, pegar, borrar). Es el que usan los buscadores en tiempo real; 'change' solo salta al perder el foco.",
    ej: 'buscador.addEventListener("input", () => {\n  render(datos.filter(d => d.includes(buscador.value)));\n});',
  },
  {
    q: "Evitar que el formulario recargue la página",
    k: "preventdefault submit formulario recarga evitar comportamiento por defecto",
    cat: "Eventos",
    js: "event.preventDefault()",
    py: null,
    que: "Los formularios recargan la página al enviarse. preventDefault() cancela ese comportamiento para que puedas procesar los datos con JavaScript.",
    ej: 'formulario.addEventListener("submit", (e) => {\n  e.preventDefault();\n  procesar();\n});',
  },
  {
    q: "Saber en qué elemento exacto se hizo clic",
    k: "event target elemento pulsado cual boton origen evento",
    cat: "Eventos",
    js: "event.target",
    py: null,
    que: "El objeto del evento trae la referencia al elemento exacto donde ocurrió, sin que tengas que rastrearlo tú.",
    ej: 'lista.addEventListener("click", (e) => {\n  console.log(e.target.textContent);\n});',
  },
  {
    q: "Escuchar clics en muchos elementos a la vez",
    k: "delegacion eventos lista dinamica muchos botones un solo listener",
    cat: "Eventos",
    js: 'padre.addEventListener("click", e => { if (e.target.matches(".btn")) ... })',
    py: null,
    que: "Delegación de eventos: escuchas en el contenedor padre y compruebas quién disparó el evento. Funciona incluso con elementos creados después.",
    ej: 'lista.addEventListener("click", (e) => {\n  if (e.target.matches(".borrar")) {\n    e.target.closest("li").remove();\n  }\n});',
  },

  // ---------- TIEMPO ----------
  {
    q: "Hacer algo cada cierto tiempo",
    k: "temporizador cronometro intervalo cada segundo setinterval reloj contador tiempo",
    cat: "Objetos del navegador",
    js: "const id = setInterval(fn, 1000)",
    py: "time.sleep(1) dentro de un bucle",
    que: "Ejecuta la función repetidamente cada X milisegundos. Guarda SIEMPRE el identificador que devuelve: sin él no podrás detenerlo después.",
    ej: "let segundos = 0;\nconst id = setInterval(() => {\n  segundos++;\n  display.textContent = segundos;\n}, 1000);",
  },
  {
    q: "Parar un temporizador",
    k: "clearinterval detener parar pausa cronometro stop intervalo",
    cat: "Objetos del navegador",
    js: "clearInterval(id)",
    py: "romper el bucle con break",
    que: "Detiene el intervalo asociado a ese identificador. Es lo que implementa el botón 'Pausar' de un cronómetro.",
    ej: "document.getElementById(\"pausar\").addEventListener(\"click\", () => {\n  clearInterval(id);\n});",
  },
  {
    q: "Hacer algo una sola vez después de X segundos",
    k: "settimeout esperar retrasar delay una vez despues de",
    cat: "Objetos del navegador",
    js: "setTimeout(fn, 2000)",
    py: "time.sleep(2)",
    que: "Ejecuta la función una única vez tras el tiempo indicado, sin bloquear el resto de la página.",
    ej: 'setTimeout(() => {\n  aviso.classList.add("oculto");\n}, 3000);',
  },

  // ---------- ALMACENAMIENTO ----------
  {
    q: "Guardar datos aunque se cierre el navegador",
    k: "localstorage persistir guardar datos no se borren recargar memoria navegador",
    cat: "CRUD completo",
    js: 'localStorage.setItem("clave", JSON.stringify(datos))',
    py: null,
    que: "localStorage guarda en el navegador de forma permanente, pero SOLO admite texto: hay que convertir cualquier array u objeto con JSON.stringify antes de guardarlo.",
    ej: 'const tareas = [{ texto: "Estudiar" }];\nlocalStorage.setItem("tareas", JSON.stringify(tareas));',
  },
  {
    q: "Leer los datos guardados al abrir la página",
    k: "localstorage getitem recuperar cargar datos guardados json parse null",
    cat: "CRUD completo",
    js: 'const datos = JSON.parse(localStorage.getItem("clave")) || []',
    py: null,
    que: "getItem devuelve null la primera vez (todavía no hay nada guardado). El '|| []' proporciona un valor por defecto para que la app no reviente.",
    ej: 'let tareas = JSON.parse(localStorage.getItem("tareas")) || [];\nrenderizar(tareas);',
  },
  {
    q: "Convertir un objeto o lista a texto y viceversa",
    k: "json stringify parse serializar convertir objeto texto guardar enviar",
    cat: "Conversión",
    js: "JSON.stringify(objeto)  ·  JSON.parse(texto)",
    py: "json.dumps(objeto)  ·  json.loads(texto)",
    que: "stringify convierte estructuras a texto JSON (para guardarlas o enviarlas) y parse hace el camino inverso, reconstruyendo el objeto.",
    ej: 'const texto = JSON.stringify({ a: 1 });  // \'{"a":1}\'\nconst obj = JSON.parse(texto);          // { a: 1 }',
  },

  // ---------- APIS / ASÍNCRONO ----------
  {
    q: "Pedir datos a una API",
    k: "fetch api peticion http get consumir servicio traer datos servidor",
    cat: "Fetch",
    js: "const res = await fetch(url);\nconst datos = await res.json();",
    py: "requests.get(url).json()",
    que: "fetch envía la petición y devuelve una promesa. Hacen falta dos esperas: una para la respuesta y otra para convertir su cuerpo a objeto con .json().",
    ej: 'async function cargar() {\n  const res = await fetch("/api/usuarios");\n  const datos = await res.json();\n  console.log(datos);\n}',
  },
  {
    q: "Esperar a que lleguen unos datos antes de seguir",
    k: "await async promesa esperar asincrono then resultado indefinido undefined",
    cat: "Promesas",
    js: "await promesa  (dentro de una función async)",
    py: "await corrutina",
    que: "await pausa esa función hasta que la promesa se resuelve, sin bloquear el resto de la página. Si ves 'undefined' o una Promise en consola, casi siempre falta un await.",
    ej: "async function main() {\n  const datos = await cargarDatos();\n  console.log(datos);\n}",
  },
  {
    q: "Controlar si una petición falló",
    k: "error catch response ok status manejo errores peticion fallo red",
    cat: "Fetch",
    js: "if (!res.ok) throw new Error(res.status)  ·  .catch(err => ...)",
    py: "if respuesta.status_code != 200:",
    que: "fetch NO lanza error con un 404 o un 500: hay que comprobar res.ok explícitamente. El .catch() solo captura fallos de red o los errores que lances tú.",
    ej: 'const res = await fetch(url);\nif (!res.ok) {\n  throw new Error("Falló: " + res.status);\n}',
  },
  {
    q: "Crear, actualizar o borrar en una API",
    k: "post put patch delete crud api enviar datos guardar servidor",
    cat: "CRUD completo",
    js: 'fetch(url, { method: "POST", body: JSON.stringify(datos) })',
    py: "requests.post(url, json=datos)",
    que: "El verbo HTTP indica la intención: POST crea, PUT reemplaza entero, PATCH cambia una parte y DELETE elimina.",
    ej: 'await fetch("/api/tareas", {\n  method: "POST",\n  headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ texto: "Nueva" }),\n});',
  },

  // ---------- CLASES ----------
  {
    q: "Crear muchos objetos con la misma forma",
    k: "clase constructor plantilla objetos instancia new poo molde",
    cat: "Clases y constructores",
    js: "class Producto { constructor(nombre) { this.nombre = nombre; } }",
    py: "class Producto:\n    def __init__(self, nombre):",
    que: "La clase es el molde: define una vez las propiedades y métodos, y luego creas tantas instancias como necesites con new.",
    ej: 'class Producto {\n  constructor(nombre, precio) {\n    this.nombre = nombre;\n    this.precio = precio;\n  }\n}\nconst p = new Producto("Café", 3);',
  },
  {
    q: "Reutilizar código entre clases",
    k: "herencia extends super clase padre hija heredar poo",
    cat: "Clases y constructores",
    js: "class Hija extends Padre { constructor(x) { super(x); } }",
    py: "class Hija(Padre):\n    def __init__(self):\n        super().__init__()",
    que: "extends hace que la clase hija herede todo lo del padre; super() invoca el constructor del padre, obligatorio antes de usar this en la hija.",
    ej: "class Animal {\n  constructor(nombre) { this.nombre = nombre; }\n}\nclass Perro extends Animal {\n  ladrar() { return this.nombre + \" ladra\"; }\n}",
  },

  // ---------- VALIDACIÓN ----------
  {
    q: "Comprobar de qué tipo es un dato",
    k: "typeof tipo dato numero texto comprobar validar es string",
    cat: "Variables",
    js: "typeof valor",
    py: "type(valor)  ·  isinstance(valor, int)",
    que: "Devuelve el tipo como texto ('string', 'number', 'boolean', 'object'...). Útil para depurar cuando algo no se comporta como esperabas.",
    ej: 'console.log(typeof "hola"); // → "string"\nconsole.log(typeof 42);     // → "number"',
  },
  {
    q: "Comprobar si algo está vacío antes de usarlo",
    k: "validar vacio null undefined comprobar existe input vacio falsy",
    cat: "Variables",
    js: "if (!valor) { ... }  ·  if (texto.trim() === \"\")",
    py: "if not valor:",
    que: "En JavaScript, valores como \"\", 0, null y undefined son 'falsy', así que !valor los cubre todos. Para inputs, trim() antes evita que los espacios cuenten como contenido.",
    ej: 'const texto = input.value.trim();\nif (!texto) {\n  return; // no hacemos nada con entradas vacías\n}',
  },
];
