// Tarjetas de repaso: primero los métodos y conceptos de metodos.html (generado
// automáticamente a partir de js/metodos.js para no duplicar el contenido a mano),
// después el método de pensamiento de pensar.html.
// Cada tarjeta lleva `lang` para poder filtrar entre JavaScript, Python y Cómo pensar.
const cardsMetodos = [
  { lang: "JavaScript", question: ".slice()  ·  JavaScript · Texto", answer: "Extrae una parte del string entre dos posiciones. Ej: \"manzana\".slice(0, 3) // → \"man\"" },
  { lang: "JavaScript", question: ".split()  ·  JavaScript · Texto", answer: "Divide un string en un array de trozos según un separador. Ej: \"a,b,c\".split(\",\") // → [\"a\", \"b\", \"c\"]" },
  { lang: "JavaScript", question: ".replace()  ·  JavaScript · Texto", answer: "Sustituye la primera coincidencia de un texto por otro. Ej: \"hola mundo\".replace(\"mundo\", \"JS\") // → \"hola JS\"" },
  { lang: "JavaScript", question: ".trim()  ·  JavaScript · Texto", answer: "Elimina los espacios en blanco del principio y el final. Ej: \"  hola  \".trim() // → \"hola\"" },
  { lang: "JavaScript", question: ".toUpperCase()  ·  JavaScript · Texto", answer: "Convierte todas las letras del string a mayúsculas. Ej: \"hola\".toUpperCase() // → \"HOLA\"" },
  { lang: "JavaScript", question: ".includes()  ·  JavaScript · Texto", answer: "Comprueba si un string contiene un fragmento de texto. Ej: \"manzana\".includes(\"man\") // → true" },
  { lang: "JavaScript", question: ".padStart()  ·  JavaScript · Texto", answer: "Rellena el string por la izquierda hasta alcanzar una longitud. Ej: \"5\".padStart(2, \"0\") // → \"05\"" },
  { lang: "Python", question: ".strip()  ·  Python · Texto", answer: "Elimina los espacios en blanco del principio y el final. Ej: \"  hola  \".strip()  # → \"hola\"" },
  { lang: "Python", question: ".split()  ·  Python · Texto", answer: "Divide un string en una lista de trozos según un separador. Ej: \"a,b,c\".split(\",\")  # → ['a', 'b', 'c']" },
  { lang: "Python", question: ".replace()  ·  Python · Texto", answer: "Sustituye todas las coincidencias de un texto por otro. Ej: \"hola mundo\".replace(\"mundo\", \"Py\")  # → \"hola Py\"" },
  { lang: "Python", question: ".upper()  ·  Python · Texto", answer: "Convierte todas las letras del string a mayúsculas. Ej: \"hola\".upper()  # → \"HOLA\"" },
  { lang: "Python", question: ".lower()  ·  Python · Texto", answer: "Convierte todas las letras del string a minúsculas. Ej: \"HOLA\".lower()  # → \"hola\"" },
  { lang: "Python", question: ".find()  ·  Python · Texto", answer: "Devuelve la posición de la primera coincidencia, o -1. Ej: \"manzana\".find(\"man\")  # → 0" },
  { lang: "Python", question: ".format()  ·  Python · Texto", answer: "Inserta valores dentro de un string usando marcadores {}. Ej: \"Hola {}\".format(\"Ana\")  # → \"Hola Ana\"" },
  { lang: "JavaScript", question: ".map()  ·  JavaScript · Arrays y objetos", answer: "Crea un nuevo array transformando cada elemento con una función. Ej: [1, 2, 3].map(x => x * 2) // → [2, 4, 6]" },
  { lang: "JavaScript", question: ".filter()  ·  JavaScript · Arrays y objetos", answer: "Crea un nuevo array solo con los elementos que cumplen una condición. Ej: [1, 2, 3, 4].filter(x => x % 2 === 0) // → [2, 4]" },
  { lang: "JavaScript", question: ".reduce()  ·  JavaScript · Arrays y objetos", answer: "Combina todos los elementos del array en un único valor acumulado. Ej: [1, 2, 3].reduce((a, b) => a + b, 0) // → 6" },
  { lang: "JavaScript", question: ".push()  ·  JavaScript · Arrays y objetos", answer: "Añade uno o más elementos al final del array. Ej: [1, 2].push(3) // el array queda [1, 2, 3]" },
  { lang: "JavaScript", question: ".pop()  ·  JavaScript · Arrays y objetos", answer: "Elimina y devuelve el último elemento del array. Ej: [1, 2, 3].pop() // → 3, el array queda [1, 2]" },
  { lang: "JavaScript", question: ".sort()  ·  JavaScript · Arrays y objetos", answer: "Ordena los elementos del array modificando el original. Ej: [3, 1, 2].sort() // → [1, 2, 3]" },
  { lang: "JavaScript", question: ".concat()  ·  JavaScript · Arrays y objetos", answer: "Une dos o más arrays en uno nuevo. Ej: [1, 2].concat([3, 4]) // → [1, 2, 3, 4]" },
  { lang: "Python", question: ".append()  ·  Python · Arrays y objetos", answer: "Añade un elemento al final de la lista. Ej: [1, 2].append(3)  # la lista queda [1, 2, 3]" },
  { lang: "Python", question: ".pop()  ·  Python · Arrays y objetos", answer: "Elimina y devuelve el último elemento de la lista. Ej: [1, 2, 3].pop()  # → 3, la lista queda [1, 2]" },
  { lang: "Python", question: ".sort()  ·  Python · Arrays y objetos", answer: "Ordena los elementos de la lista modificando la original. Ej: [3, 1, 2].sort()  # la lista queda [1, 2, 3]" },
  { lang: "Python", question: ".reverse()  ·  Python · Arrays y objetos", answer: "Invierte el orden de los elementos de la lista. Ej: [1, 2, 3].reverse()  # la lista queda [3, 2, 1]" },
  { lang: "Python", question: ".index()  ·  Python · Arrays y objetos", answer: "Devuelve la posición de la primera coincidencia de un valor. Ej: [10, 20, 30].index(20)  # → 1" },
  { lang: "Python", question: ".count()  ·  Python · Arrays y objetos", answer: "Cuenta cuántas veces aparece un valor en la lista. Ej: [1, 2, 2, 3].count(2)  # → 2" },
  { lang: "Python", question: ".extend()  ·  Python · Arrays y objetos", answer: "Añade todos los elementos de otra lista al final. Ej: [1, 2].extend([3, 4])  # → [1, 2, 3, 4]" },
  { lang: "JavaScript", question: "Number()  ·  JavaScript · Conversión", answer: "Convierte un valor a tipo número. Ej: Number(\"42\") // → 42" },
  { lang: "JavaScript", question: "String()  ·  JavaScript · Conversión", answer: "Convierte un valor a tipo texto. Ej: String(42) // → \"42\"" },
  { lang: "JavaScript", question: "parseInt()  ·  JavaScript · Conversión", answer: "Convierte un texto a número entero, ignorando decimales. Ej: parseInt(\"42px\") // → 42" },
  { lang: "JavaScript", question: "JSON.stringify()  ·  JavaScript · Conversión", answer: "Convierte un objeto o array en un texto JSON. Ej: JSON.stringify({a: 1}) // → '{\"a\":1}'" },
  { lang: "JavaScript", question: "Boolean()  ·  JavaScript · Conversión", answer: "Convierte un valor a true o false. Ej: Boolean(0) // → false" },
  { lang: "Python", question: "int()  ·  Python · Conversión", answer: "Convierte un valor a tipo entero. Ej: int(\"42\")  # → 42" },
  { lang: "Python", question: "str()  ·  Python · Conversión", answer: "Convierte un valor a tipo texto. Ej: str(42)  # → \"42\"" },
  { lang: "Python", question: "float()  ·  Python · Conversión", answer: "Convierte un valor a número decimal. Ej: float(\"3.14\")  # → 3.14" },
  { lang: "Python", question: "json.dumps()  ·  Python · Conversión", answer: "Convierte un diccionario o lista en un texto JSON. Ej: json.dumps({\"a\": 1})  # → '{\"a\": 1}'" },
  { lang: "Python", question: "bool()  ·  Python · Conversión", answer: "Convierte un valor a True o False. Ej: bool(0)  # → False" },
  { lang: "JavaScript", question: "document.querySelector()  ·  JavaScript · DOM", answer: "Devuelve el primer elemento que coincide con un selector CSS. Ej: document.querySelector(\".btn\") // primer elemento con clase btn" },
  { lang: "JavaScript", question: "document.getElementById()  ·  JavaScript · DOM", answer: "Devuelve el elemento cuyo id coincide exactamente. Ej: document.getElementById(\"titulo\") // elemento con id=\"titulo\"" },
  { lang: "JavaScript", question: ".addEventListener()  ·  JavaScript · DOM", answer: "Registra una función que se ejecuta cuando ocurre un evento. Ej: boton.addEventListener(\"click\", fn)" },
  { lang: "JavaScript", question: ".createElement()  ·  JavaScript · DOM", answer: "Crea un nuevo nodo HTML que aún no está en la página. Ej: document.createElement(\"li\") // nuevo <li> en memoria" },
  { lang: "JavaScript", question: ".appendChild()  ·  JavaScript · DOM", answer: "Inserta un nodo como último hijo de un elemento. Ej: lista.appendChild(li) // añade <li> al final de lista" },
  { lang: "JavaScript", question: ".classList.add()  ·  JavaScript · DOM", answer: "Añade una o más clases CSS a un elemento. Ej: div.classList.add(\"activo\")" },
  { lang: "JavaScript", question: ".setAttribute()  ·  JavaScript · DOM", answer: "Establece el valor de un atributo HTML en un elemento. Ej: img.setAttribute(\"alt\", \"foto\")" },
  { lang: "JavaScript", question: ".textContent  ·  JavaScript · DOM", answer: "Obtiene o establece el texto plano de un elemento, sin HTML. Ej: p.textContent = \"Hola\" // el párrafo muestra \"Hola\"" },
  { lang: "JavaScript", question: "Math.round()  ·  JavaScript · Matemáticas", answer: "Redondea un número al entero más cercano. Ej: Math.round(4.5) // → 5" },
  { lang: "JavaScript", question: "Math.random()  ·  JavaScript · Matemáticas", answer: "Genera un decimal aleatorio entre 0 (incluido) y 1 (excluido). Ej: Math.random() // → 0.3721..." },
  { lang: "JavaScript", question: "Math.max()  ·  JavaScript · Matemáticas", answer: "Devuelve el valor más alto de una lista de números. Ej: Math.max(3, 7, 2) // → 7" },
  { lang: "JavaScript", question: "Math.floor()  ·  JavaScript · Matemáticas", answer: "Redondea un número hacia abajo, al entero inferior. Ej: Math.floor(4.9) // → 4" },
  { lang: "JavaScript", question: "Math.abs()  ·  JavaScript · Matemáticas", answer: "Devuelve el valor absoluto (sin signo) de un número. Ej: Math.abs(-7) // → 7" },
  { lang: "Python", question: "round()  ·  Python · Matemáticas", answer: "Redondea un número al entero más cercano. Ej: round(4.6)  # → 5" },
  { lang: "Python", question: "random.random()  ·  Python · Matemáticas", answer: "Genera un decimal aleatorio entre 0.0 y 1.0. Ej: random.random()  # → 0.482..." },
  { lang: "Python", question: "max()  ·  Python · Matemáticas", answer: "Devuelve el valor más alto de una secuencia de números. Ej: max(3, 7, 2)  # → 7" },
  { lang: "Python", question: "math.floor()  ·  Python · Matemáticas", answer: "Redondea un número hacia abajo, al entero inferior. Ej: math.floor(4.9)  # → 4" },
  { lang: "Python", question: "abs()  ·  Python · Matemáticas", answer: "Devuelve el valor absoluto (sin signo) de un número. Ej: abs(-7)  # → 7" },
  { lang: "JavaScript", question: ".then()  ·  JavaScript · Promesas", answer: "Registra una función que se ejecuta cuando la promesa se resuelve con éxito. Ej: fetch(url).then(res => console.log(\"listo\"))" },
  { lang: "JavaScript", question: ".catch()  ·  JavaScript · Promesas", answer: "Registra una función que se ejecuta cuando la promesa es rechazada (hay un error). Ej: promesa.catch(err => console.error(err))" },
  { lang: "JavaScript", question: ".finally()  ·  JavaScript · Promesas", answer: "Registra una función que se ejecuta siempre, tanto si la promesa se resuelve como si falla. Ej: promesa.finally(() => ocultarCargando())" },
  { lang: "JavaScript", question: "Promise.all()  ·  JavaScript · Promesas", answer: "Espera a que todas las promesas del array se resuelvan, o falla en cuanto una falla. Ej: Promise.all([p1, p2]).then(([r1, r2]) => ...)" },
  { lang: "JavaScript", question: "async function  ·  JavaScript · Promesas", answer: "Declara una función que siempre devuelve una promesa y permite usar await dentro. Ej: async function cargarDatos() { ... }" },
  { lang: "JavaScript", question: "await  ·  JavaScript · Promesas", answer: "Pausa la ejecución de una función async hasta que la promesa se resuelva, sin bloquear la página. Ej: const datos = await fetch(url);" },
  { lang: "Python", question: "async def  ·  Python · Promesas", answer: "Declara una función asíncrona (una corrutina) que se puede pausar y reanudar. Ej: async def cargar_datos(): ..." },
  { lang: "Python", question: "await  ·  Python · Promesas", answer: "Espera el resultado de una corrutina sin bloquear el resto del programa. Ej: datos = await obtener_datos()" },
  { lang: "Python", question: "asyncio.run()  ·  Python · Promesas", answer: "Ejecuta una función async como punto de entrada del programa. Ej: asyncio.run(cargar_datos())" },
  { lang: "Python", question: "asyncio.gather()  ·  Python · Promesas", answer: "Ejecuta varias corrutinas a la vez y espera a que todas terminen. Ej: await asyncio.gather(tarea1(), tarea2())" },
  { lang: "JavaScript", question: "fetch()  ·  JavaScript · Fetch", answer: "Envía una petición HTTP y devuelve una promesa con la respuesta. Ej: fetch(\"https://api.ejemplo.com/datos\")" },
  { lang: "JavaScript", question: "response.json()  ·  JavaScript · Fetch", answer: "Convierte el cuerpo de la respuesta en un objeto JavaScript, devolviendo otra promesa. Ej: const datos = await respuesta.json();" },
  { lang: "JavaScript", question: "response.ok  ·  JavaScript · Fetch", answer: "Booleano que indica si la respuesta tuvo un código de estado 200-299. Ej: if (!respuesta.ok) throw new Error('Fallo en la petición');" },
  { lang: "JavaScript", question: "fetch(url, { method })  ·  JavaScript · Fetch", answer: "El segundo argumento configura el método HTTP y el cuerpo de la petición. Ej: fetch(url, { method: 'POST', body: JSON.stringify(datos) })" },
  { lang: "Python", question: "requests.get()  ·  Python · Fetch", answer: "Envía una petición HTTP GET y devuelve un objeto Response. Ej: requests.get(\"https://api.ejemplo.com/datos\")" },
  { lang: "Python", question: "response.json()  ·  Python · Fetch", answer: "Convierte el cuerpo de la respuesta en un diccionario o lista de Python. Ej: datos = respuesta.json()" },
  { lang: "Python", question: "response.status_code  ·  Python · Fetch", answer: "Número que indica el resultado de la petición (200 éxito, 404 no encontrado...). Ej: if respuesta.status_code == 200: ..." },
  { lang: "Python", question: "requests.post()  ·  Python · Fetch", answer: "Envía una petición HTTP POST, normalmente con datos en el cuerpo. Ej: requests.post(url, json={'nombre': 'Ana'})" },
  { lang: "JavaScript", question: "Leer (GET)  ·  JavaScript · CRUD completo", answer: "fetch(url) sin opciones envía una petición GET y devuelve el recurso solicitado. Ej: const datos = await (await fetch(url)).json();" },
  { lang: "JavaScript", question: "Crear (POST)  ·  JavaScript · CRUD completo", answer: "fetch(url, { method: 'POST', body }) crea un recurso nuevo con los datos enviados. Ej: fetch(url, { method: 'POST', body: JSON.stringify(nuevo) })" },
  { lang: "JavaScript", question: "Actualizar completo (PUT)  ·  JavaScript · CRUD completo", answer: "fetch(url, { method: 'PUT', body }) reemplaza todos los datos de un recurso existente. Ej: fetch(url + '/5', { method: 'PUT', body: JSON.stringify(datos) })" },
  { lang: "JavaScript", question: "Actualizar parcial (PATCH)  ·  JavaScript · CRUD completo", answer: "fetch(url, { method: 'PATCH', body }) actualiza solo una parte del recurso. Ej: fetch(url + '/5', { method: 'PATCH', body: JSON.stringify({ completada: true }) })" },
  { lang: "JavaScript", question: "Eliminar (DELETE)  ·  JavaScript · CRUD completo", answer: "fetch(url, { method: 'DELETE' }) elimina el recurso indicado en la URL. Ej: fetch(url + '/5', { method: 'DELETE' })" },
  { lang: "Python", question: "Leer (GET)  ·  Python · CRUD completo", answer: "requests.get(url) lee y devuelve el recurso solicitado. Ej: datos = requests.get(url).json()" },
  { lang: "Python", question: "Crear (POST)  ·  Python · CRUD completo", answer: "requests.post(url, json=datos) crea un recurso nuevo con los datos enviados. Ej: requests.post(url, json={'texto': 'Nueva tarea'})" },
  { lang: "Python", question: "Actualizar completo (PUT)  ·  Python · CRUD completo", answer: "requests.put(url, json=datos) reemplaza todos los datos de un recurso existente. Ej: requests.put(url + '/5', json=datos)" },
  { lang: "Python", question: "Actualizar parcial (PATCH)  ·  Python · CRUD completo", answer: "requests.patch(url, json=datos) actualiza solo una parte del recurso. Ej: requests.patch(url + '/5', json={'completada': True})" },
  { lang: "Python", question: "Eliminar (DELETE)  ·  Python · CRUD completo", answer: "requests.delete(url) elimina el recurso indicado en la URL. Ej: requests.delete(url + '/5')" },
  { lang: "JavaScript", question: "let  ·  JavaScript · Variables", answer: "Declara una variable con ámbito de bloque: solo existe dentro de las llaves {} donde se creó. Ej: if (true) { let x = 1; } // x no existe aquí fuera" },
  { lang: "JavaScript", question: "const  ·  JavaScript · Variables", answer: "Declara una variable que no se puede reasignar, aunque su contenido interno sí pueda cambiar. Ej: const lista = []; lista.push(1); // válido, no se reasigna 'lista'" },
  { lang: "JavaScript", question: "var  ·  JavaScript · Variables", answer: "Declara una variable con ámbito de función (no de bloque) y sufre 'hoisting'. Ej: if (true) { var y = 1; } console.log(y); // 1, var 'se escapa' del bloque" },
  { lang: "JavaScript", question: "typeof  ·  JavaScript · Variables", answer: "Devuelve un string con el tipo de dato de un valor. Ej: typeof \"hola\" // → \"string\"" },
  { lang: "JavaScript", question: "Hoisting  ·  JavaScript · Variables", answer: "Las declaraciones con var se mueven mentalmente al principio del ámbito, pero su asignación no. Ej: console.log(a); var a = 5; // undefined, no da error" },
  { lang: "JavaScript", question: "Ámbito de bloque  ·  JavaScript · Variables", answer: "El código dentro de {} (un if, un for...) puede tener sus propias variables con let/const, invisibles fuera. Ej: for (let i = 0; i < 3; i++) {} console.log(i); // Error: i no existe aquí" },
  { lang: "Python", question: "Asignación (=)  ·  Python · Variables", answer: "Python no distingue let/const: toda asignación crea o reemplaza una variable en su ámbito actual. Ej: x = 5, luego x = 'hola'  # válido, Python es de tipado dinámico" },
  { lang: "Python", question: "global  ·  Python · Variables", answer: "Permite modificar dentro de una función una variable definida fuera de ella. Ej: contador = 0 / def sumar(): global contador; contador += 1" },
  { lang: "JavaScript", question: "for  ·  JavaScript · Bucles", answer: "Repite un bloque de código un número conocido de veces, controlado por un contador. Ej: for (let i = 0; i < 5; i++) { console.log(i); }" },
  { lang: "JavaScript", question: "while  ·  JavaScript · Bucles", answer: "Repite un bloque mientras una condición sea verdadera, sin necesitar un contador. Ej: let i = 0; while (i < 5) { i++; }" },
  { lang: "JavaScript", question: "do...while  ·  JavaScript · Bucles", answer: "Igual que while, pero ejecuta el bloque al menos una vez antes de comprobar la condición. Ej: let i = 0; do { i++; } while (i < 5);" },
  { lang: "JavaScript", question: "for...of  ·  JavaScript · Bucles", answer: "Recorre los valores de un array (o cualquier iterable), uno a uno. Ej: for (const fruta of ['manzana', 'pera']) { console.log(fruta); }" },
  { lang: "JavaScript", question: "for...in  ·  JavaScript · Bucles", answer: "Recorre las claves (propiedades) de un objeto, no los valores de un array. Ej: for (const clave in {a: 1, b: 2}) { console.log(clave); } // 'a', 'b'" },
  { lang: "JavaScript", question: "break  ·  JavaScript · Bucles", answer: "Detiene por completo la ejecución del bucle, saliendo inmediatamente de él. Ej: for (let i = 0; i < 10; i++) { if (i === 3) break; }" },
  { lang: "JavaScript", question: "continue  ·  JavaScript · Bucles", answer: "Salta directamente a la siguiente vuelta del bucle, sin ejecutar el resto del código de esa iteración. Ej: for (let i = 0; i < 5; i++) { if (i % 2 === 0) continue; console.log(i); }" },
  { lang: "Python", question: "for ... in range()  ·  Python · Bucles", answer: "Repite un bloque un número determinado de veces generando una secuencia de números. Ej: for i in range(5): print(i)" },
  { lang: "Python", question: "while  ·  Python · Bucles", answer: "Repite un bloque mientras la condición indicada sea verdadera. Ej: i = 0 / while i < 5: i += 1" },
  { lang: "Python", question: "for elemento in lista  ·  Python · Bucles", answer: "Recorre directamente los elementos de una lista, uno a uno, sin necesitar un índice. Ej: for fruta in ['manzana', 'pera']: print(fruta)" },
  { lang: "Python", question: "break / continue  ·  Python · Bucles", answer: "break detiene el bucle por completo; continue salta a la siguiente vuelta. Ej: for i in range(10): if i == 3: break" },
  { lang: "JavaScript", question: "function saludar() {}  ·  JavaScript · Funciones", answer: "Declara una función con nombre, disponible en todo su ámbito incluso antes de la línea donde se escribe. Ej: function saludar(nombre) { return 'Hola ' + nombre; }" },
  { lang: "JavaScript", question: "Function expression  ·  JavaScript · Funciones", answer: "Guarda una función (con o sin nombre) dentro de una variable; a diferencia de la declarada, no sufre hoisting. Ej: const saludar = function (nombre) { return 'Hola ' + nombre; };" },
  { lang: "JavaScript", question: "Arrow function  ·  JavaScript · Funciones", answer: "Sintaxis corta para funciones que no tiene su propio 'this': hereda el del contexto donde se define. Ej: const sumar = (a, b) => a + b;" },
  { lang: "JavaScript", question: "Parámetro por defecto  ·  JavaScript · Funciones", answer: "Asigna un valor a un parámetro cuando no se pasa nada al llamar la función. Ej: function saludar(nombre = 'invitado') { return 'Hola ' + nombre; }" },
  { lang: "JavaScript", question: "Rest params (...args)  ·  JavaScript · Funciones", answer: "Agrupa un número indefinido de argumentos en un array dentro de la función. Ej: function sumarTodos(...numeros) { return numeros.reduce((a, b) => a + b, 0); }" },
  { lang: "JavaScript", question: "return  ·  JavaScript · Funciones", answer: "Finaliza la función y entrega un valor a quien la llamó; sin return, devuelve undefined. Ej: function doble(x) { return x * 2; }" },
  { lang: "JavaScript", question: "this en arrow vs función normal  ·  JavaScript · Funciones", answer: "En una función normal, 'this' depende de cómo se la llama; en una arrow function, 'this' es siempre el del contexto exterior. Ej: const obj = { valor: 1, normal() { return this.valor; } };" },
  { lang: "Python", question: "def  ·  Python · Funciones", answer: "Declara una función en Python. Ej: def saludar(nombre): return 'Hola ' + nombre" },
  { lang: "Python", question: "Parámetro por defecto  ·  Python · Funciones", answer: "Asigna un valor a un parámetro que se usa si no se pasa nada al llamar la función. Ej: def saludar(nombre='invitado'): return 'Hola ' + nombre" },
  { lang: "Python", question: "*args  ·  Python · Funciones", answer: "Agrupa argumentos posicionales indefinidos en una tupla dentro de la función. Ej: def sumar_todos(*numeros): return sum(numeros)" },
  { lang: "Python", question: "**kwargs  ·  Python · Funciones", answer: "Agrupa argumentos con nombre indefinidos en un diccionario dentro de la función. Ej: def config(**opciones): print(opciones)" },
  { lang: "JavaScript", question: "Object.keys()  ·  JavaScript · Arrays y objetos", answer: "Devuelve un array con los nombres de las propiedades (claves) de un objeto. Ej: Object.keys({a: 1, b: 2}) // → ['a', 'b']" },
  { lang: "JavaScript", question: "Object.values()  ·  JavaScript · Arrays y objetos", answer: "Devuelve un array con los valores de las propiedades de un objeto. Ej: Object.values({a: 1, b: 2}) // → [1, 2]" },
  { lang: "JavaScript", question: "Object.entries()  ·  JavaScript · Arrays y objetos", answer: "Devuelve un array de pares [clave, valor] a partir de un objeto. Ej: Object.entries({a: 1}) // → [['a', 1]]" },
  { lang: "JavaScript", question: "Desestructuración de arrays  ·  JavaScript · Arrays y objetos", answer: "Extrae valores de un array y los asigna a variables en una sola línea. Ej: const [primero, segundo] = [10, 20];" },
  { lang: "JavaScript", question: "Desestructuración de objetos  ·  JavaScript · Arrays y objetos", answer: "Extrae propiedades de un objeto y las asigna a variables con el mismo nombre. Ej: const { nombre, edad } = persona;" },
  { lang: "JavaScript", question: "Spread (...)  ·  JavaScript · Arrays y objetos", answer: "Expande los elementos de un array u objeto dentro de otro array, objeto o llamada de función. Ej: const copia = [...original, 4, 5];" },
  { lang: "Python", question: ".keys()  ·  Python · Arrays y objetos", answer: "Devuelve las claves de un diccionario. Ej: {'a': 1}.keys()  # → dict_keys(['a'])" },
  { lang: "Python", question: ".values()  ·  Python · Arrays y objetos", answer: "Devuelve los valores de un diccionario. Ej: {'a': 1}.values()  # → dict_values([1])" },
  { lang: "Python", question: ".items()  ·  Python · Arrays y objetos", answer: "Devuelve pares (clave, valor) de un diccionario. Ej: {'a': 1}.items()  # → dict_items([('a', 1)])" },
  { lang: "JavaScript", question: "class  ·  JavaScript · Clases y constructores", answer: "Declara una plantilla para crear objetos con propiedades y métodos comunes. Ej: class Persona { }" },
  { lang: "JavaScript", question: "constructor()  ·  JavaScript · Clases y constructores", answer: "Método especial que se ejecuta automáticamente al crear una instancia con 'new', para inicializar sus propiedades. Ej: class Persona { constructor(nombre) { this.nombre = nombre; } }" },
  { lang: "JavaScript", question: "this (en una clase)  ·  JavaScript · Clases y constructores", answer: "Hace referencia a la instancia concreta que se está creando o usando. Ej: this.nombre = nombre;" },
  { lang: "JavaScript", question: "new  ·  JavaScript · Clases y constructores", answer: "Crea una nueva instancia de una clase, ejecutando automáticamente su constructor. Ej: const ana = new Persona('Ana');" },
  { lang: "JavaScript", question: "Método de instancia  ·  JavaScript · Clases y constructores", answer: "Función definida dentro de la clase que puede usar 'this' para acceder a los datos de esa instancia concreta. Ej: class Persona { saludar() { return 'Hola, soy ' + this.nombre; } }" },
  { lang: "JavaScript", question: "extends  ·  JavaScript · Clases y constructores", answer: "Permite que una clase herede propiedades y métodos de otra clase. Ej: class Estudiante extends Persona { }" },
  { lang: "JavaScript", question: "super()  ·  JavaScript · Clases y constructores", answer: "Llama al constructor de la clase padre; es obligatorio antes de usar 'this' en el constructor de una clase hija. Ej: class Estudiante extends Persona { constructor(nombre, curso) { super(nombre); this.curso = curso; } }" },
  { lang: "JavaScript", question: "static  ·  JavaScript · Clases y constructores", answer: "Define un método o propiedad que pertenece a la clase en sí, no a sus instancias, y se llama sin crear un objeto. Ej: class Utilidades { static sumar(a, b) { return a + b; } } Utilidades.sumar(2, 3);" },
  { lang: "Python", question: "class  ·  Python · Clases y constructores", answer: "Declara una clase en Python. Ej: class Persona: pass" },
  { lang: "Python", question: "__init__  ·  Python · Clases y constructores", answer: "Método especial equivalente al constructor: se ejecuta al crear una instancia para inicializar sus atributos. Ej: class Persona: def __init__(self, nombre): self.nombre = nombre" },
  { lang: "Python", question: "self  ·  Python · Clases y constructores", answer: "Hace referencia a la instancia concreta dentro de los métodos de la clase (equivalente a 'this' en JavaScript). Ej: def saludar(self): return 'Hola, soy ' + self.nombre" },
  { lang: "Python", question: "Herencia: class Hijo(Padre)  ·  Python · Clases y constructores", answer: "Permite que una clase herede atributos y métodos de otra clase. Ej: class Estudiante(Persona): pass" },
  { lang: "Python", question: "super()  ·  Python · Clases y constructores", answer: "Llama a un método de la clase padre desde la clase hija. Ej: class Estudiante(Persona): def __init__(self, nombre, curso): super().__init__(nombre); self.curso = curso" },
  { lang: "JavaScript", question: "document.querySelectorAll()  ·  JavaScript · DOM", answer: "Devuelve una lista (NodeList) con TODOS los elementos que coinciden con un selector CSS. Ej: document.querySelectorAll('.item') // todos los elementos con clase item" },
  { lang: "JavaScript", question: ".closest()  ·  JavaScript · DOM", answer: "Busca hacia arriba en el árbol del DOM el ancestro más cercano que coincide con un selector. Ej: boton.closest('.tarjeta') // la tarjeta que contiene al botón" },
  { lang: "JavaScript", question: ".matches()  ·  JavaScript · DOM", answer: "Comprueba si un elemento concreto coincide con un selector CSS, devolviendo true o false. Ej: elemento.matches('.activo') // → true o false" },
  { lang: "JavaScript", question: "El objeto event  ·  JavaScript · Eventos", answer: "El callback de un evento recibe automáticamente un objeto con información sobre lo ocurrido. Ej: boton.addEventListener('click', (event) => console.log(event));" },
  { lang: "JavaScript", question: "event.target  ·  JavaScript · Eventos", answer: "Referencia al elemento exacto sobre el que ocurrió el evento. Ej: lista.addEventListener('click', (e) => console.log(e.target));" },
  { lang: "JavaScript", question: "event.preventDefault()  ·  JavaScript · Eventos", answer: "Cancela el comportamiento por defecto del navegador para ese evento (por ejemplo, enviar un formulario). Ej: formulario.addEventListener('submit', (e) => e.preventDefault());" },
  { lang: "JavaScript", question: "event.stopPropagation()  ·  JavaScript · Eventos", answer: "Evita que el evento siga propagándose (burbujeando) hacia los elementos padre. Ej: boton.addEventListener('click', (e) => e.stopPropagation());" },
  { lang: "JavaScript", question: "Burbujeo (bubbling)  ·  JavaScript · Eventos", answer: "Un evento disparado en un elemento hijo también se puede escuchar en sus elementos padre, porque 'sube' por el árbol del DOM. Ej: document.body.addEventListener('click', () => console.log('clic en cualquier parte'));" },
  { lang: "JavaScript", question: "Delegación de eventos  ·  JavaScript · Eventos", answer: "Escuchar el evento en un elemento padre en vez de en cada hijo, usando event.target para saber cuál se pulsó. Ej: lista.addEventListener('click', (e) => { if (e.target.tagName === 'LI') { /* ... */ } });" },
  { lang: "JavaScript", question: "window  ·  JavaScript · Objetos del navegador", answer: "Objeto global del navegador que representa la ventana; document, alert, setTimeout... son propiedades suyas. Ej: window.innerWidth // ancho visible de la ventana" },
  { lang: "JavaScript", question: "document  ·  JavaScript · Objetos del navegador", answer: "Representa la página cargada; es el punto de entrada para acceder y modificar el DOM. Ej: document.title = 'Nuevo título';" },
  { lang: "JavaScript", question: "location.href  ·  JavaScript · Objetos del navegador", answer: "Contiene (y permite cambiar) la URL actual de la página. Ej: location.href = 'https://ejemplo.com';" },
  { lang: "JavaScript", question: "setTimeout()  ·  JavaScript · Objetos del navegador", answer: "Ejecuta una función una sola vez, después de un tiempo determinado. Ej: setTimeout(() => console.log('hola'), 1000);" },
  { lang: "JavaScript", question: "alert() / confirm()  ·  JavaScript · Objetos del navegador", answer: "Muestran un cuadro de diálogo del navegador; confirm() además devuelve true o false según la elección del usuario. Ej: if (confirm('¿Seguro?')) { /* ... */ }" },
  { lang: "JavaScript", question: "export  ·  JavaScript · Módulos ES6", answer: "Hace que una variable, función o clase de un archivo esté disponible para importarla en otro. Ej: export function sumar(a, b) { return a + b; }" },
  { lang: "JavaScript", question: "export default  ·  JavaScript · Módulos ES6", answer: "Exporta un único valor principal por archivo, que se puede importar con cualquier nombre. Ej: export default function App() { }" },
  { lang: "JavaScript", question: "import { }  ·  JavaScript · Módulos ES6", answer: "Trae una exportación concreta (con nombre) de otro archivo para poder usarla. Ej: import { sumar } from './operaciones.js';" },
  { lang: "JavaScript", question: "import ... as  ·  JavaScript · Módulos ES6", answer: "Permite importar algo con un nombre distinto al que tiene en el archivo original. Ej: import { sumar as add } from './operaciones.js';" },
  { lang: "JavaScript", question: "import * as  ·  JavaScript · Módulos ES6", answer: "Importa todas las exportaciones de un archivo agrupadas en un solo objeto. Ej: import * as operaciones from './operaciones.js';" },
  { lang: "JavaScript", question: "Anotación de tipo  ·  JavaScript · TypeScript básico", answer: "Indica explícitamente qué tipo de dato puede tener una variable o parámetro. Ej: let edad: number = 25;" },
  { lang: "JavaScript", question: "interface  ·  JavaScript · TypeScript básico", answer: "Define la forma (propiedades y tipos) que debe tener un objeto. Ej: interface Persona { nombre: string; edad: number; }" },
  { lang: "JavaScript", question: "Propiedad opcional (?)  ·  JavaScript · TypeScript básico", answer: "Marca una propiedad o parámetro como opcional: puede no estar presente. Ej: interface Persona { nombre: string; apodo?: string; }" },
  { lang: "JavaScript", question: "any  ·  JavaScript · TypeScript básico", answer: "Tipo comodín que desactiva la comprobación de tipos para ese valor; se recomienda evitarlo. Ej: let dato: any = 'puede ser cualquier cosa';" },
  { lang: "JavaScript", question: "type  ·  JavaScript · TypeScript básico", answer: "Crea un alias con nombre propio para un tipo, útil para tipos complejos o reutilizados. Ej: type ID = string | number;" },
];

const cardsPensar = [
  {
    lang: "Cómo pensar",
    question: "Cómo pensar · Paso 1: Entiende el objetivo",
    answer:
      "Describe con tus propias palabras qué debe hacer la app y para quién, antes de programar nada. Pregúntate: ¿qué va a ver el usuario en pantalla cuando la app esté terminada?",
  },
  {
    lang: "Cómo pensar",
    question: "Cómo pensar · Paso 2: Identifica el estado",
    answer:
      "El estado es todo dato que cambia mientras se usa la app: un número, una lista, un booleano. Anótalo antes de escribir HTML o CSS. Pregúntate: ¿qué cambia con el tiempo o con las acciones del usuario, y qué se queda fijo?",
  },
  {
    lang: "Cómo pensar",
    question: "Cómo pensar · Paso 3: Divide el problema en piezas pequeñas",
    answer:
      "No construyas la app entera de una vez. Separa el HTML mínimo, un solo evento, una sola función. Pregúntate: si solo pudiera hacer una cosa hoy, ¿cuál sería la más pequeña que ya se pueda ver funcionando?",
  },
  {
    lang: "Cómo pensar",
    question: "Cómo pensar · Paso 4: Escribe pseudocódigo antes de código real",
    answer:
      "En español, paso a paso, sin sintaxis: 'cuando el usuario haga clic, leer el input, comprobar que no esté vacío, añadirlo a la lista'. Pregúntate: ¿podría explicarle estos pasos a alguien que no sabe programar?",
  },
  {
    lang: "Cómo pensar",
    question: "Cómo pensar · Paso 5: Identifica los eventos que disparan cambios",
    answer:
      "Casi toda interacción parte de un evento: un clic, una tecla pulsada, un envío de formulario o el paso del tiempo. Pregúntate: ¿qué acción concreta del usuario (o del reloj) debe iniciar cada cambio?",
  },
  {
    lang: "Cómo pensar",
    question: "Cómo pensar · Paso 6: Construye, prueba los casos límite y refactoriza",
    answer:
      "Implementa el camino feliz primero, luego pruébalo con datos vacíos, con 0, con texto raro. Solo cuando funciona, mejora los nombres y limpia el código repetido. Pregúntate: ¿qué pasa si el usuario no hace lo que yo esperaba?",
  },
];

const FILTROS_LANG = ["Todos", "JavaScript", "Python", "Cómo pensar"];

const cards = cardsMetodos.concat(cardsPensar);
