// ---------- Datos: la terminal de Linux, comando a comando ----------
// cmd = el comando · que = para qué sirve · ej = ejemplo real con su salida
// k = otras formas de buscarlo · win = equivalente en PowerShell (Windows)
// peligro = true si borra o rompe cosas sin preguntar

const IDEAS_BASE = [
  {
    titulo: "El prompt te dice dónde estás",
    texto:
      "ana@portatil:~/proyectos/web$ — usuario@máquina, dos puntos, la carpeta en la que estás y el símbolo. La ~ significa 'mi carpeta personal' (/home/ana). Si el símbolo es # en vez de $, estás como administrador: cuidado con lo que escribes.",
  },
  {
    titulo: "Rutas absolutas y relativas",
    texto:
      "/home/ana/web empieza por / : es absoluta, funciona desde cualquier sitio. web/css es relativa: depende de dónde estés. Los dos atajos que más se usan: . es la carpeta actual, .. es la de arriba y ~ es tu carpeta personal.",
  },
  {
    titulo: "El Tabulador es el mejor comando",
    texto:
      "Escribe tres letras y pulsa Tab: la terminal completa el nombre del archivo o de la carpeta. Dos veces seguidas, te enseña todas las opciones posibles. Se escriben muchos menos errores tecleando menos.",
  },
  {
    titulo: "Todo comando trae manual",
    texto:
      "man ls abre el manual completo (se sale con q) y ls --help enseña un resumen rápido. Antes de buscar en internet, prueba el --help: casi siempre tiene la opción que necesitas.",
  },
  {
    titulo: "Mayúsculas y espacios importan",
    texto:
      "Carpeta y carpeta son dos cosas distintas, y un espacio separa argumentos: si un nombre lleva espacios hay que escribirlo entre comillas (cd \"Mis documentos\") o escapar el espacio con \\.",
  },
  {
    titulo: "Desde Windows: WSL",
    texto:
      "wsl --install en PowerShell instala Ubuntu dentro de Windows. Tus discos aparecen en /mnt/c, y explorer.exe . abre el explorador de Windows en la carpeta en la que estés. Es la forma normal de usar Linux sin dejar Windows.",
  },
];

const COMANDOS = [
  // ---------- MOVERSE Y VER ----------
  {
    cmd: "pwd",
    cat: "Moverse y ver",
    que: "Dice en qué carpeta estás ahora mismo, con la ruta completa. Es el '¿dónde estoy?' de la terminal.",
    k: "donde estoy ruta actual carpeta directorio print working directory",
    ej: "$ pwd\n/home/ana/proyectos/web",
    win: "Get-Location  (alias: pwd)",
  },
  {
    cmd: "ls",
    cat: "Moverse y ver",
    que: "Lista lo que hay en la carpeta. Con -l añade permisos, dueño, tamaño y fecha; con -a muestra también los ocultos (los que empiezan por punto); con -h los tamaños en KB/MB.",
    k: "listar ver archivos contenido carpeta dir mostrar",
    ej: '$ ls -lah\ntotal 24K\ndrwxr-xr-x 4 ana ana 4,0K sep 13 09:12 .\n-rw-r--r-- 1 ana ana  220 sep 13 09:12 .gitignore\n-rw-r--r-- 1 ana ana 1,2K sep 13 09:10 index.html\ndrwxr-xr-x 2 ana ana 4,0K sep 13 09:11 css',
    win: "Get-ChildItem -Force  (alias: ls, dir)",
  },
  {
    cmd: "cd",
    cat: "Moverse y ver",
    que: "Cambia de carpeta. Sin nada te lleva a tu carpeta personal, .. sube un nivel y - te devuelve a la anterior en la que estabas.",
    k: "entrar carpeta cambiar directorio moverse navegar subir",
    ej: "$ cd proyectos/web     # entrar\n$ cd ..                # subir un nivel\n$ cd ~                 # a mi carpeta personal\n$ cd -                 # volver a la anterior",
    win: "Set-Location  (alias: cd)",
  },
  {
    cmd: "tree",
    cat: "Moverse y ver",
    que: "Dibuja la estructura de carpetas en forma de árbol. -L 2 limita la profundidad y -a incluye los ocultos.",
    k: "arbol estructura carpetas ver jerarquia",
    ej: "$ tree -L 2 -I node_modules\n.\n├── css\n│   └── style.css\n├── js\n│   └── main.js\n└── index.html",
    win: "tree /F",
  },
  {
    cmd: "clear",
    cat: "Moverse y ver",
    que: "Limpia la pantalla. Lo mismo que Ctrl+L, y no borra nada: el historial sigue ahí.",
    k: "limpiar pantalla borrar terminal vaciar",
    ej: "$ clear",
    win: "Clear-Host  (alias: cls)",
  },
  {
    cmd: "history",
    cat: "Moverse y ver",
    que: "Enseña el historial: los comandos que has escrito antes, numerados. !123 repite el número 123 y !! repite el último.",
    k: "historial comandos anteriores repetir ultimo que escribi",
    ej: '$ history | tail -3\n 501  npm run dev\n 502  git status\n 503  history\n$ !502          # vuelve a ejecutar git status',
    win: "Get-History  ·  h",
  },

  // ---------- VER ARCHIVOS ----------
  {
    cmd: "cat",
    cat: "Ver archivos",
    que: "Vuelca el contenido de un archivo en la pantalla. Bien para archivos cortos; para uno largo usa less.",
    k: "ver contenido archivo mostrar leer imprimir",
    ej: '$ cat .gitignore\nnode_modules/\ndist/\n.env',
    win: "Get-Content  (alias: cat, type)",
  },
  {
    cmd: "less",
    cat: "Ver archivos",
    que: "Abre un archivo largo para leerlo poco a poco: flechas y espacio para avanzar, /palabra para buscar, q para salir.",
    k: "leer archivo largo paginar visor scroll buscar dentro",
    ej: "$ less registro.log\n# dentro: /error  busca 'error'  ·  n siguiente  ·  q salir",
    win: "Get-Content archivo | more",
  },
  {
    cmd: "head / tail",
    cat: "Ver archivos",
    que: "head enseña las primeras líneas y tail las últimas (10 por defecto). tail -f deja la ventana abierta mostrando lo que se va escribiendo: es LA forma de mirar registros en vivo.",
    k: "primeras ultimas lineas log seguir en vivo registro",
    ej: "$ head -3 datos.csv\nid,nombre,precio\n1,teclado,29.9\n2,ratón,12.5\n\n$ tail -f /var/log/nginx/access.log   # se queda mirando",
    win: "Get-Content -TotalCount 3  ·  Get-Content -Tail 10 -Wait",
  },
  {
    cmd: "wc -l",
    cat: "Ver archivos",
    que: "Cuenta líneas (-l), palabras (-w) o caracteres (-c). Casi siempre se usa enchufado detrás de otro comando para contar resultados.",
    k: "contar lineas palabras cuantos resultados numero",
    ej: "$ wc -l usuarios.csv\n1043 usuarios.csv\n\n$ ls *.js | wc -l     # cuántos .js hay\n12",
    win: "(Get-Content archivo | Measure-Object -Line).Lines",
  },
  {
    cmd: "nano",
    cat: "Ver archivos",
    que: "Editor de texto sencillo dentro de la terminal. Abajo salen los atajos: Ctrl+O guarda, Ctrl+X sale.",
    k: "editar archivo editor texto modificar escribir",
    ej: "$ nano .env\n# Ctrl+O → guardar  ·  Enter → confirmar  ·  Ctrl+X → salir",
    win: "notepad archivo",
  },
  {
    cmd: "vim",
    cat: "Ver archivos",
    que: "El editor que te vas a encontrar en cualquier servidor. Lo mínimo para sobrevivir: i para escribir, Esc para dejar de escribir, :wq para guardar y salir, :q! para salir sin guardar.",
    k: "vi editor salir de vim guardar modo insercion",
    ej: "$ vim config.yml\n# i  → escribir\n# Esc → volver al modo normal\n# :wq → guardar y salir   ·   :q! → salir sin guardar",
    win: "—",
  },

  // ---------- CREAR, COPIAR, BORRAR ----------
  {
    cmd: "mkdir",
    cat: "Crear y borrar",
    que: "Crea una carpeta. Con -p crea también las carpetas intermedias que falten, y no protesta si ya existe.",
    k: "crear carpeta directorio nueva hacer",
    ej: "$ mkdir css\n$ mkdir -p src/componentes/boton   # crea los tres niveles",
    win: "New-Item -ItemType Directory -Force",
  },
  {
    cmd: "touch",
    cat: "Crear y borrar",
    que: "Crea un archivo vacío, o actualiza la fecha si ya existe. La forma más rápida de dejar un archivo preparado.",
    k: "crear archivo vacio nuevo fichero",
    ej: "$ touch index.html style.css main.js    # tres de golpe",
    win: "New-Item -ItemType File nombre",
  },
  {
    cmd: "cp",
    cat: "Crear y borrar",
    que: "Copia archivos. Para copiar una carpeta entera hace falta -r (recursivo); -i pregunta antes de pisar algo.",
    k: "copiar archivo carpeta duplicar backup respaldo",
    ej: "$ cp index.html index.backup.html\n$ cp -r css/ css-viejo/          # carpeta entera\n$ cp -i origen.txt destino.txt   # pregunta antes de pisar",
    win: "Copy-Item -Recurse  (alias: cp)",
  },
  {
    cmd: "mv",
    cat: "Crear y borrar",
    que: "Mueve un archivo… y también es la forma de renombrar: mover algo a otro nombre en la misma carpeta ES renombrarlo.",
    k: "mover renombrar archivo carpeta cambiar de nombre trasladar fichero",
    ej: "$ mv notas.txt documentos/       # mover\n$ mv viejo.txt nuevo.txt         # renombrar",
    win: "Move-Item  ·  Rename-Item",
  },
  {
    cmd: "rm",
    cat: "Crear y borrar",
    que: "Borra archivos. No hay papelera: lo que borras aquí no vuelve. -r borra carpetas enteras y -f no pregunta nada.",
    k: "borrar eliminar archivo carpeta quitar suprimir",
    ej: "$ rm temporal.txt\n$ rm -r dist/           # carpeta entera\n$ rm -i *.log           # -i pregunta uno a uno (recomendado)",
    win: "Remove-Item -Recurse -Force",
    peligro: true,
    aviso: "rm -rf / borra el sistema entero, y rm -rf * borra todo lo de la carpeta en la que estés. Antes de un rm -rf, escribe pwd y mira dos veces dónde estás.",
  },
  {
    cmd: "ln -s",
    cat: "Crear y borrar",
    que: "Crea un enlace simbólico: un 'acceso directo' que apunta a otro archivo o carpeta, sin duplicar nada.",
    k: "enlace simbolico acceso directo symlink apuntar",
    ej: "$ ln -s /var/www/html web\n$ ls -l web\nweb -> /var/www/html",
    win: "New-Item -ItemType SymbolicLink",
  },

  // ---------- BUSCAR ----------
  {
    cmd: "grep",
    cat: "Buscar",
    que: "Busca texto dentro de archivos. -r busca en toda la carpeta, -i ignora mayúsculas, -n dice el número de línea y --include limita el tipo de archivo.",
    k: "buscar texto dentro archivos palabra encontrar contenido",
    ej: '$ grep -rn "TODO" src/ --include="*.js"\nsrc/main.js:42:  // TODO: validar el formulario\nsrc/api.js:8:    // TODO: manejar el error 500',
    win: "Select-String -Pattern \"TODO\" -Path *.js",
  },
  {
    cmd: "find",
    cat: "Buscar",
    que: "Busca archivos por nombre, tipo, tamaño o fecha, recorriendo todas las subcarpetas. -name por nombre, -type f solo archivos, -mtime por fecha.",
    k: "buscar archivo por nombre encontrar fichero localizar donde esta",
    ej: '$ find . -name "*.css"\n./css/style.css\n./src/componentes/boton.css\n\n$ find . -name node_modules -prune -o -name "*.js" -print\n$ find . -type f -mtime -1        # modificados en el último día',
    win: "Get-ChildItem -Recurse -Filter *.css",
  },
  {
    cmd: "which",
    cat: "Buscar",
    que: "Dice dónde está instalado un programa y, por tanto, cuál se está ejecutando cuando hay varias versiones.",
    k: "donde esta instalado programa ruta ejecutable version",
    ej: "$ which node\n/home/ana/.nvm/versions/node/v22.11.0/bin/node",
    win: "(Get-Command node).Source",
  },
  {
    cmd: "Ctrl + R",
    cat: "Buscar",
    que: "Busca en el historial mientras escribes: pulsas Ctrl+R, escribes tres letras del comando y aparece. Otra vez Ctrl+R para ir a la coincidencia anterior, Enter para ejecutar.",
    k: "buscar historial comando anterior atajo reverse search",
    ej: "(reverse-i-search)`npm ru': npm run dev",
    win: "Ctrl+R (también funciona en PowerShell)",
  },

  // ---------- TUBERÍAS Y REDIRECCIÓN ----------
  {
    cmd: "|",
    cat: "Tuberías y redirección",
    que: "La tubería: enchufa la salida de un comando a la entrada del siguiente. Es la idea central de la terminal: programas pequeños encadenados hacen cosas grandes.",
    k: "pipe tuberia encadenar combinar comandos enchufar",
    ej: "$ ls *.js | wc -l                    # contar archivos js\n$ cat acceso.log | grep 404 | wc -l  # cuántos 404 hay",
    win: "| (igual en PowerShell, pero pasa objetos)",
  },
  {
    cmd: "> y >>",
    cat: "Tuberías y redirección",
    que: "Guardan la salida en un archivo: > lo crea o lo SOBRESCRIBE entero, >> añade al final sin borrar lo que había.",
    k: "guardar salida archivo redirigir escribir volcar",
    ej: '$ ls -l > listado.txt        # crea (o pisa) el archivo\n$ echo "otra línea" >> listado.txt   # añade al final',
    win: "> y >>  (igual)",
  },
  {
    cmd: "2> y 2>&1",
    cat: "Tuberías y redirección",
    que: "Los errores viajan por un canal distinto al de la salida normal. 2> guarda solo los errores, 2>&1 los junta con la salida, y 2>/dev/null los tira a la basura.",
    k: "errores salida separar silenciar stderr ocultar",
    ej: "$ comando 2> errores.log        # solo los errores al archivo\n$ comando > todo.log 2>&1       # salida y errores juntos\n$ find / -name x 2>/dev/null    # ignora los 'permiso denegado'",
    win: "2>$null",
  },
  {
    cmd: "&& y ||",
    cat: "Tuberías y redirección",
    que: "&& ejecuta lo siguiente SOLO si lo anterior fue bien; || solo si falló; y ; los ejecuta uno detrás de otro pase lo que pase.",
    k: "encadenar comandos si sale bien condicional secuencia",
    ej: "$ npm run build && npm run deploy   # solo despliega si el build fue bien\n$ ping -c1 web.com || echo 'sin conexión'",
    win: "; if ($?) { ... }  (en PowerShell 5.1 no existe &&)",
  },
  {
    cmd: "xargs",
    cat: "Tuberías y redirección",
    que: "Coge la lista que le llega y la convierte en argumentos del comando siguiente. Es el pegamento entre find/grep y cualquier otro comando.",
    k: "aplicar comando a lista resultados convertir argumentos bucle",
    ej: '$ find . -name "*.log" | xargs rm      # borra todos los .log\n$ ls *.png | xargs -I{} cp {} copias/  # {} es cada nombre',
    win: "| ForEach-Object { ... }",
  },
  {
    cmd: "sort / uniq",
    cat: "Tuberías y redirección",
    que: "sort ordena líneas (-n numérico, -r al revés) y uniq quita repetidas seguidas, por eso casi siempre va detrás de sort. uniq -c cuenta cuántas veces aparece cada una.",
    k: "ordenar lineas quitar duplicados contar repetidos ranking",
    ej: "$ cut -d' ' -f1 acceso.log | sort | uniq -c | sort -rn | head -5\n  842 66.249.66.1\n  310 192.168.1.20",
    win: "Sort-Object  ·  Get-Unique  ·  Group-Object",
  },
  {
    cmd: "sed",
    cat: "Tuberías y redirección",
    que: "Sustituye texto sin abrir el archivo. s/viejo/nuevo/g cambia todas las apariciones; con -i modifica el archivo en el sitio.",
    k: "reemplazar sustituir texto masivo cambiar todas apariciones",
    ej: '$ sed "s/localhost/produccion.com/g" config.js      # muestra el resultado\n$ sed -i "s/localhost/produccion.com/g" config.js   # lo cambia de verdad',
    win: "(Get-Content x) -replace 'a','b' | Set-Content x",
  },
  {
    cmd: "awk",
    cat: "Tuberías y redirección",
    que: "Trabaja por columnas: $1 es la primera, $2 la segunda… Perfecto para sacar campos de un log o de un CSV y hacer cuentas.",
    k: "columnas campos csv extraer sumar procesar texto",
    ej: '$ awk -F, \'{ suma += $3 } END { print suma }\' ventas.csv\n15420\n\n$ ps aux | awk \'{ print $2, $11 }\'   # PID y programa',
    win: "Import-Csv  ·  ForEach-Object { $_.campo }",
  },

  // ---------- PERMISOS ----------
  {
    cmd: "chmod",
    cat: "Permisos",
    que: "Cambia los permisos. Los tres números son dueño, grupo y resto: 4 leer + 2 escribir + 1 ejecutar. 755 es lo normal para carpetas y programas, 644 para archivos y 600 para secretos.",
    k: "permisos cambiar ejecutable script no tengo permiso denegado",
    ej: "$ chmod +x desplegar.sh     # hacerlo ejecutable\n$ chmod 644 index.html      # dueño lee/escribe, resto solo lee\n$ chmod 600 .env            # solo el dueño, ni mirar los demás",
    win: "icacls  (el modelo de permisos es distinto)",
  },
  {
    cmd: "chown",
    cat: "Permisos",
    que: "Cambia quién es el dueño de un archivo o carpeta. Casi siempre hace falta sudo y -R para aplicarlo a todo lo de dentro.",
    k: "dueño propietario cambiar usuario grupo permisos carpeta",
    ej: "$ sudo chown -R ana:ana /var/www/mi-web",
    win: "icacls /setowner",
  },
  {
    cmd: "sudo",
    cat: "Permisos",
    que: "Ejecuta ESE comando como administrador. sudo !! repite el último comando con permisos, que es lo que quieres el 90 % de las veces que ves 'permiso denegado'.",
    k: "administrador root permisos denegado superusuario admin",
    ej: "$ apt install git\nE: Permiso denegado\n$ sudo !!            # repite con sudo delante",
    win: "Ejecutar PowerShell como administrador",
    peligro: true,
    aviso: "Nunca pegues un comando con sudo sacado de internet sin entender qué hace: con sudo, un error no avisa ni pregunta.",
  },
  {
    cmd: "whoami / id",
    cat: "Permisos",
    que: "whoami dice con qué usuario estás; id añade los grupos a los que perteneces, que es lo que decide a qué tienes acceso.",
    k: "quien soy usuario actual grupos permisos cuenta",
    ej: "$ whoami\nana\n$ id\nuid=1000(ana) gid=1000(ana) grupos=1000(ana),27(sudo),999(docker)",
    win: "whoami  (igual)",
  },

  // ---------- PROCESOS ----------
  {
    cmd: "ps aux",
    cat: "Procesos",
    que: "Lista todos los procesos en marcha con su PID (el número que los identifica), quién los lanzó y cuánta CPU y memoria gastan.",
    k: "procesos ver que esta corriendo programas abiertos pid",
    ej: "$ ps aux | grep node\nana  4821  1.2  0.8  node server.js\nana  5102  0.0  0.0  grep node",
    win: "Get-Process  (alias: ps)",
  },
  {
    cmd: "top / htop",
    cat: "Procesos",
    que: "El monitor en vivo: qué consume CPU y memoria, ordenado de mayor a menor. htop es la versión bonita y con ratón (se instala aparte). q para salir.",
    k: "monitor recursos cpu memoria consumo ralentizado lento",
    ej: "$ htop\n# F6 ordenar  ·  F9 matar un proceso  ·  q salir",
    win: "Get-Process | Sort-Object CPU -Descending  ·  Administrador de tareas",
  },
  {
    cmd: "kill",
    cat: "Procesos",
    que: "Cierra un proceso por su PID. kill -9 lo mata sin contemplaciones (último recurso: no le da tiempo a guardar nada).",
    k: "matar proceso cerrar programa colgado forzar terminar",
    ej: "$ kill 4821          # pedirle que se cierre\n$ kill -9 4821       # matarlo a la fuerza\n$ pkill -f 'node server.js'   # por nombre, sin buscar el PID",
    win: "Stop-Process -Id 4821  ·  Stop-Process -Name node",
  },
  {
    cmd: "lsof -i :3000",
    cat: "Procesos",
    que: "Dice qué programa está ocupando un puerto. Es LA respuesta a 'Error: port 3000 is already in use'.",
    k: "puerto ocupado en uso quien usa address in use liberar",
    ej: "$ lsof -i :3000\nCOMMAND  PID USER   NAME\nnode    4821  ana  *:3000 (LISTEN)\n$ kill 4821",
    win: "Get-NetTCPConnection -LocalPort 3000",
  },
  {
    cmd: "&  ·  jobs  ·  fg",
    cat: "Procesos",
    que: "Un & al final lanza el comando en segundo plano y te devuelve la terminal. jobs lista lo que tienes ahí y fg lo trae de vuelta al frente. Ctrl+Z pausa lo que esté corriendo.",
    k: "segundo plano background recuperar pausar proceso terminal ocupada",
    ej: "$ npm run dev &\n[1] 4821\n$ jobs\n[1]+  Running   npm run dev &\n$ fg %1        # traerlo al frente",
    win: "Start-Job  ·  Get-Job  ·  Receive-Job",
  },

  // ---------- DISCO Y SISTEMA ----------
  {
    cmd: "df -h",
    cat: "Disco y sistema",
    que: "Cuánto espacio queda en cada disco, en unidades legibles (-h). Lo primero que se mira cuando algo falla sin motivo aparente.",
    k: "espacio disco lleno libre cuanto queda particiones",
    ej: "$ df -h\nS.ficheros  Tamaño Usado Disp Uso% Montado en\n/dev/sda2     234G  180G  42G  82% /",
    win: "Get-PSDrive  ·  Get-Volume",
  },
  {
    cmd: "du -sh",
    cat: "Disco y sistema",
    que: "Cuánto ocupa una carpeta. -s da solo el total y -h lo pone en MB/GB. Combinado con sort encuentra al culpable del disco lleno.",
    k: "tamaño carpeta cuanto ocupa pesado espacio que ocupa mas",
    ej: "$ du -sh node_modules/\n412M\tnode_modules/\n\n$ du -sh * | sort -rh | head -5    # las 5 más gordas",
    win: "(Get-ChildItem -Recurse | Measure-Object Length -Sum).Sum",
  },
  {
    cmd: "free -h",
    cat: "Disco y sistema",
    que: "Memoria RAM usada y libre. La columna 'disponible' es la que importa: Linux usa la RAM sobrante como caché a propósito.",
    k: "memoria ram libre usada cuanta consumo",
    ej: "$ free -h\n              total   usado   libre  disponible\nMem:           15Gi   6,2Gi   1,1Gi       8,4Gi",
    win: "Get-CimInstance Win32_OperatingSystem",
  },
  {
    cmd: "uname -a  ·  lsb_release -a",
    cat: "Disco y sistema",
    que: "Qué sistema y qué versión estás usando. Lo primero que te van a preguntar si pides ayuda con un error.",
    k: "version sistema distribucion que linux tengo kernel",
    ej: "$ lsb_release -a\nDescription: Ubuntu 24.04.1 LTS\n$ uname -r\n6.8.0-45-generic",
    win: "Get-ComputerInfo  ·  winver",
  },

  // ---------- RED ----------
  {
    cmd: "curl",
    cat: "Red",
    que: "Hace peticiones HTTP desde la terminal: probar una API, descargar un archivo, comprobar que un servidor responde. -i enseña las cabeceras, -X el método y -d los datos.",
    k: "peticion api probar http descargar request rest",
    ej: '$ curl -s https://api.github.com/users/octocat | head -3\n$ curl -X POST localhost:3000/api/tareas \\\n    -H "Content-Type: application/json" \\\n    -d \'{"titulo":"Probar curl"}\'',
    win: "Invoke-RestMethod  ·  curl.exe (el real también está)",
  },
  {
    cmd: "wget",
    cat: "Red",
    que: "Descarga archivos por URL. -c continúa una descarga cortada y -O le pone el nombre que quieras.",
    k: "descargar archivo url internet bajar fichero",
    ej: "$ wget https://ejemplo.com/datos.zip\n$ wget -c https://ejemplo.com/grande.iso   # reanudar",
    win: "Invoke-WebRequest -OutFile",
  },
  {
    cmd: "ping",
    cat: "Red",
    que: "Comprueba si una máquina responde y cuánto tarda. -c 4 manda solo cuatro y para (si no, sigue hasta Ctrl+C).",
    k: "conexion internet responde red latencia probar host",
    ej: "$ ping -c 4 google.com\n64 bytes from 142.250.200.110: icmp_seq=1 ttl=115 time=12.4 ms",
    win: "Test-Connection  ·  ping",
  },
  {
    cmd: "ip a  ·  ss -tulpn",
    cat: "Red",
    que: "ip a enseña tus direcciones IP; ss -tulpn lista qué puertos están abiertos y qué programa escucha en cada uno. Sustituyen a los antiguos ifconfig y netstat.",
    k: "ip direccion puertos abiertos escuchando red configuracion",
    ej: "$ ip -brief a\nlo    UNKNOWN  127.0.0.1/8\nwlp3s0 UP      192.168.1.42/24\n\n$ ss -tulpn | grep 3000\ntcp LISTEN 0 511 *:3000 users:((\"node\",pid=4821))",
    win: "ipconfig  ·  Get-NetTCPConnection",
  },
  {
    cmd: "ssh",
    cat: "Red",
    que: "Abre una terminal en otra máquina (un servidor, una Raspberry). Con -i se indica la clave privada y con -p un puerto distinto del 22.",
    k: "conectar servidor remoto acceder maquina terminal remota vps",
    ej: "$ ssh ana@192.168.1.50\n$ ssh -i ~/.ssh/id_ed25519 ubuntu@mi-servidor.com\n$ ssh-keygen -t ed25519      # crear la pareja de claves\n$ ssh-copy-id ana@servidor   # dejar tu clave allí y no volver a escribir contraseña",
    win: "ssh (incluido en Windows 10+)",
  },
  {
    cmd: "scp / rsync",
    cat: "Red",
    que: "Copian archivos entre tu máquina y un servidor. rsync es el bueno: solo manda lo que ha cambiado y puede reanudar.",
    k: "copiar servidor subir bajar archivos remoto sincronizar desplegar",
    ej: "$ scp index.html ana@servidor:/var/www/\n$ rsync -avz --delete dist/ ana@servidor:/var/www/mi-web/\n# -a conserva permisos · -v cuenta lo que hace · -z comprime",
    win: "scp  ·  robocopy (local)",
  },

  // ---------- PAQUETES ----------
  {
    cmd: "apt",
    cat: "Paquetes",
    que: "El instalador de Debian y Ubuntu. update refresca la lista de paquetes (no instala nada) y upgrade actualiza lo instalado; hay que hacer los dos, en ese orden.",
    k: "instalar programa ubuntu debian actualizar paquete software",
    ej: "$ sudo apt update && sudo apt upgrade\n$ sudo apt install git curl htop\n$ apt search sass\n$ sudo apt remove htop",
    win: "winget install  ·  choco install",
  },
  {
    cmd: "dnf / pacman",
    cat: "Paquetes",
    que: "Lo mismo que apt pero en otras familias: dnf en Fedora y RHEL, pacman en Arch y Manjaro.",
    k: "instalar fedora arch manjaro rhel paquete programa",
    ej: "$ sudo dnf install git          # Fedora\n$ sudo pacman -S git            # Arch\n$ sudo pacman -Syu              # actualizar todo",
    win: "winget install",
  },
  {
    cmd: "snap / flatpak",
    cat: "Paquetes",
    que: "Aplicaciones empaquetadas con todo lo que necesitan dentro. Útiles cuando el paquete oficial está viejo; a cambio ocupan más y arrancan algo más lentas.",
    k: "instalar aplicacion grafica programa version nueva contenedor",
    ej: "$ sudo snap install code --classic\n$ flatpak install flathub org.gimp.GIMP",
    win: "winget  ·  Microsoft Store",
  },

  // ---------- COMPRIMIR ----------
  {
    cmd: "tar",
    cat: "Comprimir",
    que: "Empaqueta y comprime carpetas. Regla para no mirarlo cada vez: -c crear, -x extraer, -z comprimir con gzip, -v ir contando, -f el nombre del archivo.",
    k: "comprimir descomprimir carpeta empaquetar backup tar gz extraer",
    ej: "$ tar -czvf copia.tar.gz mi-carpeta/     # crear\n$ tar -xzvf copia.tar.gz                 # extraer\n$ tar -tzvf copia.tar.gz                 # ver qué hay dentro sin extraer",
    win: "Compress-Archive  ·  tar (incluido en Windows 10+)",
  },
  {
    cmd: "zip / unzip",
    cat: "Comprimir",
    que: "El formato que entiende todo el mundo, también Windows. -r incluye las subcarpetas y -d extrae en una carpeta concreta.",
    k: "zip comprimir descomprimir carpeta archivo windows",
    ej: "$ zip -r proyecto.zip mi-carpeta/\n$ unzip proyecto.zip -d destino/",
    win: "Compress-Archive  ·  Expand-Archive",
  },

  // ---------- ENTORNO ----------
  {
    cmd: "echo $VARIABLE",
    cat: "Entorno y scripts",
    que: "Enseña el valor de una variable de entorno. $PATH es la lista de carpetas donde el sistema busca los programas: si un comando 'no se encuentra', suele ser que no está ahí.",
    k: "variable entorno path ver valor no se encuentra comando",
    ej: '$ echo $HOME\n/home/ana\n$ echo $PATH | tr ":" "\\n" | head -3\n/home/ana/.nvm/versions/node/v22.11.0/bin\n/usr/local/bin\n/usr/bin',
    win: "$env:PATH",
  },
  {
    cmd: "export",
    cat: "Entorno y scripts",
    que: "Crea una variable de entorno para esta sesión. Si quieres que sobreviva a cerrar la terminal, va en ~/.bashrc o ~/.zshrc.",
    k: "variable entorno crear definir api key token configurar",
    ej: '$ export API_KEY="abc123"\n$ node -e "console.log(process.env.API_KEY)"\nabc123\n\n# permanente:\n$ echo \'export API_KEY="abc123"\' >> ~/.bashrc && source ~/.bashrc',
    win: "$env:API_KEY = \"abc123\"",
  },
  {
    cmd: "alias",
    cat: "Entorno y scripts",
    que: "Inventa tu propio comando corto para uno largo. Puesto en ~/.bashrc, está siempre disponible.",
    k: "atajo comando propio acortar personalizar bashrc",
    ej: "$ alias gs='git status'\n$ alias ll='ls -lah'\n$ alias ..='cd ..'\n# para que dure: añádelos a ~/.bashrc",
    win: "Set-Alias  ·  function gs { git status }",
  },
  {
    cmd: "source ~/.bashrc",
    cat: "Entorno y scripts",
    que: "Recarga el archivo de configuración de la terminal sin cerrarla. Necesario cada vez que tocas .bashrc, .zshrc o .profile.",
    k: "recargar configuracion bashrc aplicar cambios perfil terminal",
    ej: "$ nano ~/.bashrc\n$ source ~/.bashrc     # ahora sí valen los cambios",
    win: ". $PROFILE",
  },
  {
    cmd: "#!/bin/bash",
    cat: "Entorno y scripts",
    que: "La primera línea de un script dice con qué programa hay que ejecutarlo. Luego hay que darle permiso de ejecución con chmod +x y se lanza con ./nombre.sh.",
    k: "script bash crear ejecutar shebang automatizar sh",
    ej: '#!/bin/bash\nset -e                     # para a la primera que algo falle\necho "Desplegando..."\nnpm run build\nrsync -az dist/ servidor:/var/www/\n\n$ chmod +x desplegar.sh\n$ ./desplegar.sh',
    win: ".ps1 + Set-ExecutionPolicy",
  },

  // ---------- GIT ----------
  {
    cmd: "git status",
    cat: "Git",
    que: "Qué ha cambiado, qué está preparado para el commit y en qué rama estás. El comando que más se escribe del mundo: ante la duda, status.",
    k: "estado cambios rama que he tocado git",
    ej: "$ git status -sb\n## main...origin/main [ahead 1]\n M css/style.css\n?? js/nuevo.js",
    win: "igual (Git es el mismo en todos lados)",
  },
  {
    cmd: "git add / commit",
    cat: "Git",
    que: "add elige qué cambios entran en la foto y commit la guarda con un mensaje. -m pone el mensaje en la misma línea.",
    k: "guardar cambios confirmar commit preparar añadir",
    ej: '$ git add css/style.css        # un archivo\n$ git add .                    # todo lo cambiado\n$ git commit -m "Arregla el menú en móvil"',
    win: "igual",
  },
  {
    cmd: "git push / pull",
    cat: "Git",
    que: "push sube tus commits al repositorio remoto y pull se trae los de los demás. Antes de empezar a trabajar, pull; al terminar, push.",
    k: "subir bajar cambios remoto github sincronizar",
    ej: "$ git pull\n$ git push\n$ git push -u origin mi-rama     # la primera vez de una rama nueva",
    win: "igual",
  },
  {
    cmd: "git switch / branch",
    cat: "Git",
    que: "branch lista las ramas, switch cambia de rama y switch -c crea una nueva y salta a ella. Sustituyen al antiguo checkout, que hacía demasiadas cosas.",
    k: "rama crear cambiar branch nueva funcionalidad",
    ej: "$ git branch\n* main\n  arreglo-menu\n$ git switch -c nueva-funcion    # crear y cambiar\n$ git switch main                # volver",
    win: "igual",
  },
  {
    cmd: "git log --oneline",
    cat: "Git",
    que: "El historial en una línea por commit. --graph dibuja las ramas y -5 limita a los cinco últimos.",
    k: "historial commits ver cambios anteriores quien hizo",
    ej: "$ git log --oneline --graph -5\n* 766c3cb Botones de categoría y ejemplos senior\n* 1bc3270 Reconocer corchetes y símbolos",
    win: "igual",
  },
  {
    cmd: "git diff",
    cat: "Git",
    que: "Enseña exactamente qué líneas han cambiado. Sin nada, lo que aún no has añadido; con --staged, lo que ya está preparado para el commit.",
    k: "ver diferencias cambios lineas comparar antes de commit",
    ej: "$ git diff css/style.css\n-  color: #333;\n+  color: var(--ink);\n\n$ git diff --staged    # lo que entraría en el commit",
    win: "igual",
  },
  {
    cmd: "git restore",
    cat: "Git",
    que: "Deshace cambios: sin --staged tira los cambios del archivo (¡no se recuperan!); con --staged solo lo saca de la zona de preparación y conserva lo escrito.",
    k: "deshacer cambios descartar volver atras recuperar archivo",
    ej: "$ git restore --staged archivo.js   # quitarlo del add, sin perder nada\n$ git restore archivo.js            # tirar los cambios del archivo",
    win: "igual",
    peligro: true,
    aviso: "git restore archivo.js (sin --staged) borra lo que hayas escrito y no está en ningún commit: eso no lo recupera ni Git.",
  },

  // ---------- WINDOWS / WSL ----------
  {
    cmd: "wsl",
    cat: "Windows y WSL",
    que: "Arranca Linux dentro de Windows. wsl --install lo instala la primera vez, wsl -l -v lista lo que tienes y wsl --shutdown lo apaga si se atasca.",
    k: "linux en windows instalar ubuntu subsistema wsl2",
    ej: "PS> wsl --install           # la primera vez (reinicia)\nPS> wsl -l -v\n  NAME      STATE    VERSION\n* Ubuntu    Running  2\nPS> wsl --shutdown",
    win: "—",
  },
  {
    cmd: "/mnt/c  ·  explorer.exe .",
    cat: "Windows y WSL",
    que: "Desde WSL, tus discos de Windows están en /mnt/c, /mnt/d… Y explorer.exe . abre el explorador de Windows justo en la carpeta en la que estés.",
    k: "acceder discos windows desde linux carpeta explorador ruta",
    ej: "$ cd /mnt/c/Users/ana/Documentos\n$ explorer.exe .        # abre esta carpeta en el explorador\n$ code .                # y esto la abre en VS Code",
    win: "—",
  },
  {
    cmd: "Los comandos en PowerShell",
    cat: "Windows y WSL",
    que: "PowerShell tiene los mismos alias (ls, cd, cat, pwd) pero por debajo son otros comandos y pasan objetos, no texto. Las opciones NO son las mismas: ls -la falla.",
    k: "powershell windows equivalente diferencia alias cmd",
    ej: "PS> Get-ChildItem -Force      # el ls -la de Windows\nPS> Select-String \"TODO\" *.js  # el grep\nPS> Get-Content -Tail 10 -Wait log.txt   # el tail -f",
    win: "—",
  },
];

const ATAJOS = [
  ["Tab", "Completa el nombre del archivo o comando. Dos veces: enseña todas las opciones."],
  ["Ctrl + C", "Corta lo que esté corriendo ahora mismo. La salida de emergencia de todo."],
  ["Ctrl + D", "Cierra la sesión o la entrada (equivale a escribir exit)."],
  ["Ctrl + R", "Busca hacia atrás en el historial mientras escribes."],
  ["Ctrl + L", "Limpia la pantalla, igual que clear."],
  ["Ctrl + A / Ctrl + E", "Ir al principio / al final de la línea."],
  ["Ctrl + U / Ctrl + K", "Borrar desde el cursor hacia atrás / hacia delante."],
  ["Ctrl + W", "Borrar la última palabra escrita."],
  ["Ctrl + Z", "Pausa el proceso y te devuelve la terminal (fg lo reanuda)."],
  ["↑ / ↓", "Recorrer los comandos anteriores."],
  ["!!", "El comando anterior entero. sudo !! lo repite como administrador."],
  ["!$", "El último argumento del comando anterior (mkdir web && cd !$)."],
];
