// Buenas prácticas, escritas para leerse rápido: regla corta, un porqué de
// una línea y el antes/después en código. nivel "esencial" = lo que aplica
// casi siempre; "extra" = matices que se activan con el interruptor.

const CHECKLIST = [
  "Si el código se repite dos veces, hazlo una función.",
  "El nombre de una función es un verbo: dice qué hace.",
  "Una función, una sola responsabilidad.",
  "Devuelve valores; no toques cosas de fuera.",
  "const por defecto, let solo si va a cambiar.",
  "Nada de números sueltos: constantes con nombre.",
  "Sal pronto de la función en vez de anidar ifs.",
  "Separa calcular de pintar en pantalla.",
  "Comenta el porqué, no el qué.",
];

const COMO_HACER_FUNCION = [
  "Identifica el código que quieres extraer.",
  "Crea una función vacía y copia el código dentro.",
  "Mira qué variables de fuera está usando ese código.",
  "Convierte cada una de esas variables en un parámetro.",
  "Los valores fijos que haya dentro, también a parámetros.",
  "Si generalizas dos casos parecidos, valora un parámetro que elija el camino.",
  "Pon valores por defecto en los parámetros que se pueda.",
  "Decide qué valor debe devolver y retórnalo.",
  "Ajusta el código hasta que funcione aislado.",
  "Sustituye el código original por una llamada a la función.",
];

const TEMAS_PRACTICAS = [
  {
    id: "funciones",
    nombre: "Funciones",
    emoji: "🔧",
    resumen: "Cuándo crearlas, cómo nombrarlas y hasta dónde deben llegar.",
    porque: [
      "Para no repetir código (DRY: <em>Don't Repeat Yourself</em>).",
      "Para poder reutilizar lo que ya resolviste una vez.",
      "Para que el código se lea como una lista de intenciones, no de detalles.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "El nombre es un verbo que dice qué hace",
        porque: "Si hay que leer el cuerpo para saber qué hace, el nombre ha fallado.",
        mal: "function datos(x) { ... }\nfunction proceso2(a, b) { ... }",
        bien: "function calcularTotal(precios) { ... }\nfunction validarEmail(email) { ... }",
      },
      {
        nivel: "esencial",
        regla: "Una función, una sola responsabilidad",
        porque: "Si al describirla necesitas un 'y', probablemente son dos funciones.",
        mal: "function guardarTarea(texto) {\n  if (!texto) return;        // valida\n  tareas.push(texto);        // guarda\n  lista.innerHTML += texto;  // y pinta\n}",
        bien: "function esValida(texto) { return texto.trim() !== \"\"; }\nfunction guardarTarea(texto) { tareas.push(texto); }\nfunction pintarTareas(tareas) { /* ... */ }",
      },
      {
        nivel: "esencial",
        regla: "Devuelve un valor en vez de tocar cosas de fuera",
        porque: "Una función que devuelve algo se puede probar, reutilizar y encadenar.",
        mal: "let total = 0;\nfunction sumar(precios) {\n  total = precios.reduce((a, b) => a + b, 0); // modifica fuera\n}",
        bien: "function sumar(precios) {\n  return precios.reduce((a, b) => a + b, 0);\n}\nconst total = sumar(precios);",
      },
      {
        nivel: "esencial",
        regla: "Que sea pura siempre que puedas",
        porque: "Misma entrada → misma salida, sin efectos colaterales. Así nunca sorprende.",
        mal: "function aplicarDescuento(carrito) {\n  carrito.total *= 0.9; // modifica el objeto que le pasaron\n}",
        bien: "function aplicarDescuento(carrito) {\n  return { ...carrito, total: carrito.total * 0.9 };\n}",
      },
      {
        nivel: "esencial",
        regla: "Valores por defecto en vez de comprobar undefined",
        porque: "Cubres el caso normal sin llenar la función de comprobaciones.",
        mal: "function saludar(nombre) {\n  if (nombre === undefined) nombre = \"invitado\";\n  return \"Hola \" + nombre;\n}",
        bien: 'function saludar(nombre = "invitado") {\n  return "Hola " + nombre;\n}',
      },
      {
        nivel: "esencial",
        regla: "No mezcles calcular con pintar en pantalla",
        porque: "La lógica separada se puede probar sin navegador y reutilizar en otro sitio.",
        mal: "function calcularIva(precio) {\n  const total = precio * 1.21;\n  document.getElementById(\"total\").textContent = total; // 👈 sobra\n}",
        bien: 'function calcularIva(precio) {\n  return precio * 1.21;\n}\ndisplay.textContent = calcularIva(precio);',
      },
      {
        nivel: "esencial",
        regla: "Corta mejor que larga",
        porque: "Si no cabe en una pantalla, cuesta seguirla; y suele estar haciendo de más.",
        mal: "// 80 líneas dentro de un solo addEventListener",
        bien: "boton.addEventListener(\"click\", () => {\n  const datos = leerFormulario();\n  if (!esValido(datos)) return;\n  guardar(datos);\n  pintar(datos);\n});",
      },
      {
        nivel: "extra",
        regla: "Pocos parámetros; si son muchos, pasa un objeto",
        porque: "Con un objeto no importa el orden y cada valor se lee con su nombre.",
        mal: 'crearUsuario("Ana", "ana@mail.com", 30, "Madrid", true);\n// ¿qué era el true? ¿y si me salto uno?',
        bien: 'crearUsuario({\n  nombre: "Ana",\n  email: "ana@mail.com",\n  edad: 30,\n  activo: true,\n});',
      },
      {
        nivel: "extra",
        regla: "Genérica antes que específica",
        porque: "Lo que hoy es un valor fijo dentro, mañana es un parámetro que la hace reutilizable.",
        mal: "function precioConIvaEspana(precio) {\n  return precio * 1.21;\n}",
        bien: "function aplicarImpuesto(precio, tasa = 0.21) {\n  return precio * (1 + tasa);\n}",
      },
      {
        nivel: "extra",
        regla: "Cuidado con los parámetros bandera",
        porque:
          "Sirven para unificar dos casos casi iguales, pero si el booleano parte la función en dos caminos completos, en realidad son dos funciones.",
        mal: "function renderizar(lista, esModoEdicion) {\n  if (esModoEdicion) { /* 20 líneas */ }\n  else { /* otras 20 distintas */ }\n}",
        bien: "function renderizarLectura(lista) { /* ... */ }\nfunction renderizarEdicion(lista) { /* ... */ }",
      },
    ],
  },
  {
    id: "nombres",
    nombre: "Nombres y variables",
    emoji: "🏷️",
    resumen: "El 80% de la legibilidad se decide aquí, y es gratis.",
    porque: [
      "Un buen nombre ahorra un comentario.",
      "Vas a leer ese código muchas más veces de las que lo escribes.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "const por defecto, let solo si va a cambiar",
        porque: "Al leer un const ya sabes que ese valor no te va a cambiar bajo los pies.",
        mal: 'let usuarios = [];\nlet MAX = 10; // ninguno de los dos se reasigna',
        bien: "const usuarios = [];\nconst MAX = 10;\nlet contador = 0; // este sí cambia",
      },
      {
        nivel: "esencial",
        regla: "Nombres que se puedan leer en voz alta",
        porque: "Abreviar ahorra tres segundos al escribir y cuesta minutos al releer.",
        mal: "const d = 7;\nconst tmp = u.filter(x => x.a);",
        bien: "const diasRestantes = 7;\nconst usuariosActivos = usuarios.filter(u => u.activo);",
      },
      {
        nivel: "esencial",
        regla: "Nada de números mágicos",
        porque: "Un número suelto no explica nada; con nombre, se explica solo y se cambia en un sitio.",
        mal: "if (intentos > 3) bloquear();\nsetTimeout(avisar, 86400000);",
        bien: "const MAX_INTENTOS = 3;\nconst UN_DIA_MS = 24 * 60 * 60 * 1000;\n\nif (intentos > MAX_INTENTOS) bloquear();",
      },
      {
        nivel: "extra",
        regla: "Los booleanos se leen como una pregunta",
        porque: "Así el if suena a frase: si está activo, si tiene stock.",
        mal: "const activo = true;\nconst stock = false;",
        bien: "const estaActivo = true;\nconst tieneStock = false;\n\nif (tieneStock) { /* ... */ }",
      },
      {
        nivel: "extra",
        regla: "El nombre dice qué guarda, no cómo se obtuvo",
        porque: "Si cambias la implementación, el nombre no se queda mintiendo.",
        mal: "const listaFiltradaConReduceYMap = ...;",
        bien: "const productosDisponibles = ...;",
      },
    ],
  },
  {
    id: "arrays",
    nombre: "Listas y datos",
    emoji: "🧺",
    resumen: "Transformar en vez de acumular a mano, y no romper lo que te prestan.",
    porque: [
      "Casi toda app real es una lista que se filtra, se transforma y se pinta.",
      "La mayoría de bugs con arrays vienen de modificar el original sin querer.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "map/filter cuando transformas o seleccionas",
        porque: "El nombre del método ya dice la intención; el bucle manual hay que descifrarlo.",
        mal: "const caros = [];\nfor (let i = 0; i < precios.length; i++) {\n  if (precios[i] > 10) caros.push(precios[i]);\n}",
        bien: "const caros = precios.filter(p => p > 10);",
      },
      {
        nivel: "esencial",
        regla: "No modifiques el array que te pasan",
        porque: "Quien te lo prestó no espera encontrárselo cambiado. Devuelve uno nuevo.",
        mal: "function ordenar(lista) {\n  return lista.sort(); // sort MUTA el original\n}",
        bien: "function ordenar(lista) {\n  return [...lista].sort();\n}",
      },
      {
        nivel: "extra",
        regla: "Si solo buscas uno, usa find",
        porque: "filter recorre entero y devuelve una lista; find para en cuanto lo encuentra.",
        mal: "const encontrado = usuarios.filter(u => u.id === id)[0];",
        bien: "const encontrado = usuarios.find(u => u.id === id);",
      },
      {
        nivel: "extra",
        regla: "Comprueba si está vacío antes de pintar",
        porque: "Una lista vacía sin mensaje parece una app rota.",
        mal: "tareas.forEach(pintar); // si no hay ninguna, pantalla en blanco",
        bien: 'if (tareas.length === 0) {\n  lista.textContent = "Todavía no hay tareas";\n  return;\n}\ntareas.forEach(pintar);',
      },
    ],
  },
  {
    id: "condicionales",
    nombre: "Condicionales",
    emoji: "🔀",
    resumen: "Menos anidación, menos negaciones, menos sorpresas.",
    porque: [
      "Cada nivel de indentación es un nivel más que sostener en la cabeza.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "Sal pronto en vez de anidar",
        porque: "Despachas los casos raros al principio y el camino normal queda sin indentar.",
        mal: "function guardar(texto) {\n  if (texto) {\n    if (texto.length < 100) {\n      if (!existe(texto)) {\n        tareas.push(texto);\n      }\n    }\n  }\n}",
        bien: "function guardar(texto) {\n  if (!texto) return;\n  if (texto.length >= 100) return;\n  if (existe(texto)) return;\n\n  tareas.push(texto);\n}",
      },
      {
        nivel: "esencial",
        regla: "Compara siempre con ===",
        porque: "== convierte tipos por su cuenta y produce comparaciones que no esperabas.",
        mal: 'if (edad == "18") { }   // true aunque uno sea texto\nif (0 == "") { }        // también true 😵',
        bien: "if (edad === 18) { }",
      },
      {
        nivel: "extra",
        regla: "Evita las negaciones dobles",
        porque: "'Si no está inactivo' obliga a traducir mentalmente; 'si está activo' no.",
        mal: "if (!usuario.noActivo) { /* ... */ }",
        bien: "if (usuario.estaActivo) { /* ... */ }",
      },
      {
        nivel: "extra",
        regla: "Ternario solo si cabe en una línea",
        porque: "Anidar ternarios es la forma más rápida de hacer ilegible una condición.",
        mal: 'const t = a ? (b ? "x" : c ? "y" : "z") : "w";',
        bien: 'const mensaje = tieneStock ? "Disponible" : "Agotado";',
      },
    ],
  },
  {
    id: "dom",
    nombre: "DOM",
    emoji: "🌳",
    resumen: "Buscar una vez, pintar de forma segura y no mezclar con la lógica.",
    porque: [
      "Tocar el DOM es lo más lento de una app: conviene hacerlo lo justo.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "Guarda el selector en una variable",
        porque: "Buscar el mismo elemento una y otra vez es trabajo repetido y ruido visual.",
        mal: 'document.getElementById("total").textContent = 0;\ndocument.getElementById("total").classList.add("ok");',
        bien: 'const total = document.getElementById("total");\ntotal.textContent = 0;\ntotal.classList.add("ok");',
      },
      {
        nivel: "esencial",
        regla: "textContent por defecto, innerHTML solo si controlas el contenido",
        porque: "innerHTML interpreta etiquetas: con texto del usuario es un agujero de seguridad.",
        mal: "li.innerHTML = tareaDelUsuario; // si escribe HTML, se ejecuta",
        bien: "li.textContent = tareaDelUsuario;",
      },
      {
        nivel: "esencial",
        regla: "Cambia clases, no estilos sueltos",
        porque: "El aspecto vive en el CSS; el JS solo decide en qué estado está.",
        mal: 'div.style.backgroundColor = "red";\ndiv.style.border = "2px solid darkred";',
        bien: 'div.classList.add("error"); // el CSS define cómo se ve un error',
      },
      {
        nivel: "extra",
        regla: "Vacía antes de repintar",
        porque: "Si no, cada renderizado añade encima y los elementos se duplican.",
        mal: "function render(items) {\n  items.forEach(i => lista.appendChild(crearLi(i)));\n}",
        bien: 'function render(items) {\n  lista.innerHTML = "";\n  items.forEach(i => lista.appendChild(crearLi(i)));\n}',
      },
    ],
  },
  {
    id: "eventos",
    nombre: "Eventos",
    emoji: "🖱️",
    resumen: "Escuchar en el sitio correcto y no dispararse mil veces.",
    porque: [
      "Los eventos son la puerta de entrada de todo lo que hace el usuario.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "Delega cuando hay muchos elementos",
        porque: "Un solo listener en el padre funciona incluso con elementos creados después.",
        mal: 'document.querySelectorAll(".borrar").forEach(b => {\n  b.addEventListener("click", borrar); // los nuevos se quedan fuera\n});',
        bien: 'lista.addEventListener("click", (e) => {\n  if (e.target.matches(".borrar")) borrar(e);\n});',
      },
      {
        nivel: "esencial",
        regla: "preventDefault en el submit del formulario",
        porque: "Si no, la página se recarga y pierdes los datos antes de procesarlos.",
        mal: 'form.addEventListener("submit", () => {\n  procesar(); // no llega: la página ya se recargó\n});',
        bien: 'form.addEventListener("submit", (e) => {\n  e.preventDefault();\n  procesar();\n});',
      },
      {
        nivel: "extra",
        regla: "Frena los eventos que se disparan mucho",
        porque: "input, scroll o resize saltan decenas de veces por segundo.",
        mal: 'buscador.addEventListener("input", filtrarDiezMilItems);',
        bien: "let temporizador;\nbuscador.addEventListener(\"input\", () => {\n  clearTimeout(temporizador);\n  temporizador = setTimeout(filtrar, 200);\n});",
      },
    ],
  },
  {
    id: "async",
    nombre: "Asincronía y APIs",
    emoji: "🌐",
    resumen: "Esperar bien, comprobar siempre y no encadenar en serie sin motivo.",
    porque: [
      "Todo lo que sale de tu app (una API, un archivo) puede tardar o fallar.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "async/await antes que cadenas de .then",
        porque: "Se lee de arriba abajo, como el código normal.",
        mal: "fetch(url)\n  .then(res => res.json())\n  .then(datos => pintar(datos))\n  .catch(err => console.error(err));",
        bien: "try {\n  const res = await fetch(url);\n  const datos = await res.json();\n  pintar(datos);\n} catch (err) {\n  mostrarError(err);\n}",
      },
      {
        nivel: "esencial",
        regla: "Comprueba res.ok: fetch no falla con un 404",
        porque: "fetch solo rechaza si no hay red. Un 404 o un 500 llegan como respuesta 'correcta'.",
        mal: "const res = await fetch(url);\nconst datos = await res.json(); // si fue 404, revienta aquí",
        bien: 'const res = await fetch(url);\nif (!res.ok) throw new Error("Error " + res.status);\nconst datos = await res.json();',
      },
      {
        nivel: "esencial",
        regla: "Avisa al usuario mientras carga y si falla",
        porque: "Una pantalla congelada sin explicación se percibe como una app rota.",
        mal: "const datos = await cargar(); // el usuario no ve nada durante 3 segundos",
        bien: 'mostrarCargando();\ntry {\n  pintar(await cargar());\n} catch {\n  mostrarMensaje("No se pudo cargar. Inténtalo de nuevo.");\n} finally {\n  ocultarCargando();\n}',
      },
      {
        nivel: "extra",
        regla: "Peticiones independientes, en paralelo",
        porque: "Si no dependen entre sí, esperar una detrás de otra suma tiempos sin razón.",
        mal: "const usuarios = await fetch(u1);\nconst productos = await fetch(u2); // espera a la anterior sin necesidad",
        bien: "const [usuarios, productos] = await Promise.all([\n  fetch(u1),\n  fetch(u2),\n]);",
      },
    ],
  },
  {
    id: "organizacion",
    nombre: "Organización y comentarios",
    emoji: "🗂️",
    resumen: "Que el que abra el archivo dentro de seis meses (tú) lo entienda.",
    porque: [
      "El código se escribe una vez y se lee muchas.",
    ],
    practicas: [
      {
        nivel: "esencial",
        regla: "Comenta el porqué, no el qué",
        porque: "El qué ya lo dice el código; el porqué se pierde para siempre si no lo escribes.",
        mal: "// sumamos 1 al contador\ncontador++;",
        bien: "// El backend cuenta desde 1, no desde 0\ncontador++;",
      },
      {
        nivel: "esencial",
        regla: "Datos y lógica en archivos distintos",
        porque: "Puedes cambiar el contenido sin tocar el comportamiento, y al revés.",
        mal: "// app.js: 800 líneas con los datos, la lógica y el pintado juntos",
        bien: "// datos.js  → los arrays y objetos\n// app.js    → qué se hace con ellos",
      },
      {
        nivel: "extra",
        regla: "Las constantes, arriba del archivo",
        porque: "Lo configurable se encuentra de un vistazo, sin bucear por el código.",
        mal: "// ... 200 líneas ...\nsetTimeout(cerrar, 5000); // ¿por qué 5000?",
        bien: "const TIEMPO_AVISO_MS = 5000;\n// ... más abajo ...\nsetTimeout(cerrar, TIEMPO_AVISO_MS);",
      },
      {
        nivel: "extra",
        regla: "Borra el código muerto",
        porque: "El control de versiones ya lo recuerda por ti; comentado solo estorba.",
        mal: "// function viejaVersion() {\n//   ... 40 líneas comentadas ...\n// }",
        bien: "// (borrado: si hace falta, está en el historial de git)",
      },
    ],
  },
];
